using Aetheris.Kernel.Core.Brep;
using Aetheris.Kernel.Core.Math;
using System.Text.Json.Serialization;

namespace Aetheris.Kernel.Firmament.Piping;

public enum RouteAnchorKind { Endpoint, HardWaypoint, AutoWaypoint }
public enum RouteProvenance { Explicit, AutoGenerated, LocallyRerouted }
public enum PipingConnectionType { Generic, Flange, Weld, Threaded }

public sealed record PipePolicyIr(string StableId, string Name, double OuterDiameterMm, double WallThicknessMm, string Material)
{
    public double RadiusMm => OuterDiameterMm / 2d;
    public double InnerDiameterMm => OuterDiameterMm - 2d * WallThicknessMm;
}

/// <summary>A piping port is an Assembly Interface with a bounded circular compatibility contract.</summary>
public sealed record PipingPortInterfaceIr(
    string StableId, string Name, Point3D Position, Vector3D OutwardDirection,
    string PipePolicy, PipingConnectionType ConnectionType, string DatumFrame,
    string? Equipment = null, string? OwnerKeepOut = null, double NozzleLengthMm = 0);

public sealed record PipingEquipmentIr(string StableId, string Name, string KeepOut);

public sealed record PipingConnectionIr(
    string StableId, string Name, string FromPort, string ToPort, string PipePolicy,
    string? Service, bool ReducerRequired, bool AdapterRequired);

public sealed record KeepOutIr(string StableId, string Name, Point3D Minimum, Point3D Maximum, string SourceConcept)
{
    public KeepOutIr Inflate(double distance) => new(StableId, Name,
        new(Minimum.X - distance, Minimum.Y - distance, Minimum.Z - distance),
        new(Maximum.X + distance, Maximum.Y + distance, Maximum.Z + distance), SourceConcept);
}

public sealed record RouteAnchorIr(string StableId, int Ordinal, Point3D Point, RouteAnchorKind Kind, bool Locked = false);
public sealed record RouteSegmentIr(string StableId, int Ordinal, string StartAnchor, string EndAnchor, double LengthMm, bool Locked);
public sealed record RouteTurnIr(string StableId, int AnchorOrdinal, string Fitting, double BendRadiusMm, double AngleDegrees = 90d);

public sealed record RouteIr(
    string StableId, string Name, string Connection, string StartInterface, string EndInterface,
    IReadOnlyList<RouteAnchorIr> Anchors, IReadOnlyList<RouteSegmentIr> Segments,
    IReadOnlyList<RouteTurnIr> Turns, IReadOnlyList<int> LockedSegmentOrdinals,
    RouteProvenance Provenance, string SourceProvenance)
{
    public double CenterlineLengthMm => Segments.Sum(x => x.LengthMm);
}

public sealed record RouteRequestIr(
    string StableId, string Name, string Connection, PipingPortInterfaceIr From, PipingPortInterfaceIr To,
    PipePolicyIr PipePolicy, IReadOnlyList<KeepOutIr> KeepOuts, double ClearanceMm,
    IReadOnlyList<Point3D> HardWaypoints, double BendRadiusMm = 50d);

public enum RouteFailureKind
{
    NoCollisionFreePath,
    EndpointDirectionImpossible,
    ClearanceTooLarge,
    HardWaypointUnreachable,
    RoutingRegionDisconnected,
    LockedIntervalPreventsSolution
}

public sealed record RouteProposalIr(
    string StableId, string Request, bool IsSuccess, IReadOnlyList<RouteAnchorIr> Anchors,
    double LengthMm, int ElbowCount, double MinimumClearanceMm, double Cost,
    IReadOnlyList<string> Diagnostics, RouteFailureKind? FailureKind,
    string Algorithm = "adaptive-coordinate-grid-a-star");

public sealed record PipeSegmentComponentIr(
    string StableId, string Route, int Ordinal, string PipePolicy, string Material,
    string StartInterface, string EndInterface, double CenterlineLengthMm, double CutLengthMm, [property: JsonIgnore] BrepBody Body);

public sealed record FittingInterfaceIr(string StableId, string Name, Point3D Position, Vector3D OutwardDirection);
public sealed record PipingFittingComponentIr(
    string StableId, string Route, int AnchorOrdinal, string ProductIdentity, string PipePolicy,
    IReadOnlyList<FittingInterfaceIr> Interfaces, [property: JsonIgnore] BrepBody Body);

public sealed record EquipmentNozzleComponentIr(
    string StableId, string Port, string Equipment, string OwnerKeepOut, string PipePolicy,
    Point3D RootPosition, Point3D TipPosition,
    FittingInterfaceIr EquipmentInterface, FittingInterfaceIr PipeInterface,
    [property: JsonIgnore] BrepBody Body);

public sealed record PipingMateIr(
    string StableId, string Port, string NozzleInterface, string PipeInterface,
    Point3D Position, Vector3D NozzleOutwardDirection, Vector3D PipeOutwardDirection,
    bool Coincident, bool DirectionsOpposed);

public sealed record PipingKeepOutExemptionIr(
    string StableId, string Port, string Nozzle, string KeepOut, string Scope);

public sealed record PipingBomEntry(string ProductIdentity, string PipePolicy, string Material, int Quantity, IReadOnlyList<string> Components);
public sealed record PipeCutListEntry(string GroupId, string PipePolicy, double OuterDiameterMm, double WallThicknessMm, string Material, double CutLengthMm, int Quantity, IReadOnlyList<string> Segments);
public sealed record PipingAssemblyIr(string StableId, string Name, IReadOnlyList<string> Definitions, IReadOnlyList<string> Occurrences, IReadOnlyList<string> Interfaces);
public sealed record PipingTimingReport(double ParseBindMilliseconds, double ObstaclePreparationMilliseconds, double GraphCreationAndSearchMilliseconds, double SimplificationMilliseconds, double FittingRealizationMilliseconds, double BrepAndStepMilliseconds);

public sealed record PipingReport(
    string Schema, string PipingSystem, PipingAssemblyIr Assembly,
    IReadOnlyList<PipePolicyIr> PipePolicies, IReadOnlyList<PipingEquipmentIr> Equipment,
    IReadOnlyList<PipingPortInterfaceIr> Ports,
    IReadOnlyList<PipingConnectionIr> Connections, IReadOnlyList<KeepOutIr> KeepOuts,
    IReadOnlyList<RouteProposalIr> RouteProposals, IReadOnlyList<RouteIr> Routes,
    IReadOnlyList<PipeSegmentComponentIr> PipeSegments, IReadOnlyList<PipingFittingComponentIr> Fittings,
    IReadOnlyList<EquipmentNozzleComponentIr> Nozzles, IReadOnlyList<PipingMateIr> Mates,
    IReadOnlyList<PipingKeepOutExemptionIr> KeepOutExemptions,
    IReadOnlyList<PipingBomEntry> Bom, IReadOnlyList<PipeCutListEntry> CutList,
    double MinimumVerifiedClearanceMm, bool GeometryClearanceVerified, bool ComponentsEnclosed,
    int BodyCount, int CylinderCount, int TorusCount, int PlaneCount, IReadOnlyList<double> Bounds,
    string StepSha256, bool StepReimportSucceeded, string MaterializationRoute,
    string? RoutingReportArtifactPath, string? CutListArtifactPath, string? BomArtifactPath,
    PipingTimingReport Timings);

public sealed record PipingCompilationResult(
    bool IsSuccess, string? StepText, PipingReport? Report, IReadOnlyList<string> Diagnostics,
    IReadOnlyList<PipeSegmentComponentIr>? RealizedSegments = null,
    IReadOnlyList<PipingFittingComponentIr>? RealizedFittings = null,
    IReadOnlyList<EquipmentNozzleComponentIr>? RealizedNozzles = null);
