<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aetheris.Forge\Aetheris.Forge.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Materials\Database\aetheris-materials-x1.sqlite"
             Condition="Exists('Materials\Database\aetheris-materials-x1.sqlite')"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest"
             Pack="true"
             PackagePath="contentFiles/any/any/Materials/aetheris-materials-x1.sqlite"
             PackageCopyToOutput="true"
             Link="Materials\aetheris-materials-x1.sqlite" />
    <None Include="build\Aetheris.Kernel.StandardLibrary.targets"
          Pack="true"
          PackagePath="buildTransitive\Aetheris.Kernel.StandardLibrary.targets" />
  </ItemGroup>
</Project>
