using System.Diagnostics;
using System.Security.Cryptography;
using System.Text.Json;
using Aetheris.Geometry;
using Aetheris.Reconstruction;

var root = FindRoot();
var sourcePath = Path.GetFullPath(args.Length > 0 ? args[0] : Path.Combine(root, ".tmp", "bunny-m0-source", "bunny", "reconstruction", "bun_zipper.ply"));
var output = Path.GetFullPath(args.Length > 1 ? args[1] : Path.Combine(root, "artifacts", "local", "evidence", "geometry", "bunny-m3"));
if (!File.Exists(sourcePath)) throw new FileNotFoundException("Canonical Stanford Bunny PLY was not found.", sourcePath);
Directory.CreateDirectory(output); var total = Stopwatch.StartNew(); var watch = Stopwatch.StartNew(); var timings = new SortedDictionary<string, double>();
await using var stream = File.OpenRead(sourcePath); var mesh = PlyTriangleSurfaceLoader.LoadAscii(stream, "bunny/reconstruction/bun_zipper.ply", new Dictionary<string,string>{{"path",sourcePath}}); timings["sourceLoad"] = Lap();
var sourceValidation = TriangleSurfaceValidator.Validate(mesh); timings["sourceValidation"] = Lap();
var (rawField, rawSummary) = StructuredSurfaceRecovery.EstimateField(mesh); timings["crossField"] = Lap();
var (field, regularization) = CrossFieldRegularizer.Regularize(mesh, rawField, 8); timings["fieldRegularization"] = Lap();
var atlas = QuadAtlasRecovery.Build(mesh, field); timings["globalLayoutAndPanelFit"] = Lap();
var canonical = QuadAtlasSurfaceMeshLowering.Lower(mesh, atlas); timings["nativeBoundedPatchLowering"] = Lap();
var coarsening = StructuralPanelCoarsener.Coarsen(mesh, atlas); timings["boundedPairCoarseningAndResidualExtraction"] = Lap();

var boundaryPanels = atlas.Charts.Count(chart => chart.OrderedSides.Any(use => atlas.Seams.Single(seam => seam.StableId == use.SeamId).IsSourceBoundary));
var singularVertices = atlas.Singularities.SelectMany(x => x.SourceVertices).ToHashSet(); var topologyPanels = atlas.Charts.Count(chart => chart.CornerVertices.Any(singularVertices.Contains));
var parameterPanels = atlas.Charts.Count(chart => chart.AngleDistortionDegrees >= 75); var mergeSourcePanels = coarsening.MergedPairCount * 2;
var classifications = new Dictionary<string,int>
{
    ["real topology / detected singularity proximity"] = topologyPanels,
    ["source boundary"] = boundaryPanels,
    ["parameterization limitation (angle distortion >= 75 degrees)"] = parameterPanels,
    ["likely removable through admitted bounded merge"] = mergeSourcePanels,
    ["local triangle-pairing artifact / unproven necessity"] = Math.Max(0, atlas.Charts.Count - new[]{topologyPanels,boundaryPanels,parameterPanels,mergeSourcePanels}.Max())
};
Write("m2-oversegmentation-audit.json", new { m2Panels=34692, measuredM3PairPanels=atlas.Charts.Count, classificationsAreOverlapping=true, classifications, explanation="M2 creates exactly one Panel per matched adjacent triangle pair; panel existence therefore follows source face density before topology, feature, or residual necessity is tested.", mergePressure=new{neighborPairs=atlas.Seams.Count(x=>x.ChartUses.Count==2),admittedPairs=coarsening.MergedPairCount,coarsening.RejectedTopology,coarsening.RejectedFeature,coarsening.RejectedParameterization,coarsening.RejectedResidual}, representatives=coarsening.RepresentativeDecisions.Take(20)});
Write("field-regularization-summary.json", regularization);
Write("singularity-summary.json", new { m2=1603,m3=regularization.OutputSingularities,cancelled=regularization.CancelledNet,regularization.RetainedFeatureFaces,regularization.RetainedBoundaryFaces,regularization.GlobalIndexPreserved,uncertainCases=regularization.OutputSingularities, note="Retained cases remain heuristic winding evidence; no certification is claimed." });
Write("global-layout-summary.json", new { algorithm="deterministic Edmonds blossom maximum-cardinality matching after hard disk/four-corner/foldover filtering",transitionTrianglesBefore=67,transitionTrianglesAfter=atlas.UnresolvedTriangles.Count,parityLowerBound=mesh.Triangles.Count%2,explanation="An odd source face count makes zero impossible for pair-only layout; eliminating the last transition requires a larger chart operation.",additionalMatchedPairs=atlas.Charts.Count-34692,transitionFacesRemoved=67-atlas.UnresolvedTriangles.Count,meanFieldDeviationDegrees=Mean(atlas.Seams.Select(x=>x.FieldDeviationDegrees)),atlas.DeterministicHash,judgment="Judgment scores geometric options before the exact graph stage; it does not replace matching."});
Write("panel-coarsening-summary.json", new { m2PanelCount=34692,m3PairAtlasPanels=atlas.Charts.Count,structuralPanelCount=coarsening.Panels.Count,coarsening.MergedPairCount,coarsening.MergeRatio,coarsening.ExactCandidateCount,coarsening.DeferredCandidateCount,averageM2PanelsPerStructuralPanel=34692d/coarsening.Panels.Count,sourceTrianglesPerStructuralPanel=mesh.Triangles.Count/(double)coarsening.Panels.Count,globallyLowerable=false,scope="bounded audit of the 1,000 smoothest best-neighbor proposals; disjoint two-Panel unions only",nextBlocker="batched/cached projection followed by arbitrary multi-chart four-sided parameterization plus global residual seam reconciliation" });
var mapped = coarsening.Panels.Where(x=>x.ResidualField is not null).ToArray();
Write("residual-field-summary.json", new { offsetType="bounded 3 x 3 piecewise-bilinear scalar grid along base unit normal",normalType="bounded piecewise-bilinear explicit target-normal grid; differential-only authority",domain="authored base Panel rectangular ParametricDomain",evidence="Sampled closest-point projection with explicit normal/tangential decomposition",seamPolicy="zero scalar offset at structural seams in the bounded coarsening stage",residualMappedPanels=mapped.Length,controls=mapped.Sum(x=>x.ResidualField!.ControlCount),storageBytesEstimate=mapped.Sum(x=>x.ResidualField!.ControlCount)*sizeof(double),baseRms=Rms(mapped.Select(x=>x.BaseRms)),correctedRms=Rms(mapped.Select(x=>x.CorrectedRms)),offsetRms=Rms(mapped.SelectMany(x=>GridValues(x.ResidualField!.PositionOffset!))),offsetMaximum=Max(mapped.SelectMany(x=>GridValues(x.ResidualField!.PositionOffset!))),maximumTangentialResidual=Max(mapped.Select(x=>x.MaximumTangentialResidual)),authority=new{offset="moves reconstructed geometry",normal="never moves geometry; interpreted differential/shading normal only"} });
var m2Parameter = new { mean=51.69,p95=85.11,maximum=89.99 }; var m3Angles=atlas.Charts.Select(x=>x.AngleDistortionDegrees).ToArray();
Write("parameterization-summary.json", new { m2=m2Parameter,m3=new{mean=Mean(m3Angles),p95=P(m3Angles,.95),maximum=Max(m3Angles),aspectMean=Mean(atlas.Charts.Select(x=>x.AspectRatio)),aspectP95=P(atlas.Charts.Select(x=>x.AspectRatio),.95),aspectMaximum=Max(atlas.Charts.Select(x=>x.AspectRatio)),foldovers=atlas.Charts.Sum(x=>x.Foldovers)},method="four-corner Coons/bilinear; bounded pair coarsening does not yet solve arbitrary multi-chart UV relaxation",improvedMaterially=false });
Write("continuity-summary.json", new { internalCracks=canonical.InternalCrackGroups,intentionalOpenLoops=canonical.IntentionalOpenBoundaryLoops,canonical.NonManifoldEdgeCount,residualSeamPolicy="shared corrected corner position within explicit tolerance; disagreement rejects lowering; bounded coarsener fits zero seam offsets",coarsenedAtlasGloballyReconciled=false });
Write("mesh-summary.json", new { vertices=canonical.Document.Vertices.Count,cells=canonical.QuadCount+canonical.TriangleCount,quads=canonical.QuadCount,triangles=canonical.TriangleCount,nGons=0,quadPercentage=100d*canonical.QuadCount/(canonical.QuadCount+canonical.TriangleCount),canonical.InternalCrackGroups,intentionalLoops=canonical.IntentionalOpenBoundaryLoops,canonical.NonManifoldEdgeCount,validation=canonical.ValidationStatus,nativeBoundedPatchSupports=canonical.Document.Patches.Count(x=>x.Support.Kind==Aetheris.Kernel.Core.Brep.Tessellation.SurfaceMeshSupportKind.BoundedParametricPatch),planeProxyCount=canonical.Document.Patches.Count(x=>x.ChartId?.StartsWith("quad-")==true&&x.Support.Kind==Aetheris.Kernel.Core.Brep.Tessellation.SurfaceMeshSupportKind.Plane),canonical.DeterministicHash,authority="globally valid pair atlas; coarsened diagnostic atlas is not substituted until its global seam network exists" });
Write("quality-comparison.json", new { m2=new{sourcePanelRms=.00006273042597053603,remeshSourceRms=.000030452953532103108,normalMeanDegrees=4.2433,normalRmsDegrees=14.7434,normalMaxDegrees=90},m3=new{positionAndNormalCanonicalReevaluation="not repeated: native support changes carrier, not authored Panel geometry",representativeCoarsenedBaseRms=Rms(coarsening.Panels.Where(x=>x.SourceChartIds.Count>1).Select(x=>x.BaseRms)),representativeCoarsenedCorrectedRms=Rms(coarsening.Panels.Where(x=>x.SourceChartIds.Count>1).Select(x=>x.CorrectedRms)),maximumTangentialResidual=Max(coarsening.Panels.Select(x=>x.MaximumTangentialResidual))},honesty="No improved global normal-tail or Hausdorff claim is made without a residual-aware globally coarsened remesh." });
Write("representation-compression.json", new { sourceTriangles=mesh.Triangles.Count,m2Panels=34692,m3PairAtlasPanels=atlas.Charts.Count,m3StructuralCandidates=coarsening.Panels.Count,residualControls=mapped.Sum(x=>x.ResidualField!.ControlCount),derivedCanonicalCells=canonical.QuadCount+canonical.TriangleCount,sourceTrianglesPerStructuralPanel=mesh.Triangles.Count/(double)coarsening.Panels.Count,m2PanelsPerM3Panel=34692d/coarsening.Panels.Count,sourceMeshBytes=new FileInfo(sourcePath).Length,m3ResidualBytesEstimate=mapped.Sum(x=>x.ResidualField!.ControlCount)*sizeof(double) });
Write("judgment-summary.json", new { uses=new[]{new{decision="adjacent-face quad route",hardConstraints="disk/four corners/nonfolded",score="field .50 + shape .35 + normal .15",candidateCount=atlas.JudgmentTraces.Sum(x=>x.CandidateCount),winner="trace-specific"},new{decision="base-only versus scalar offset grid",hardConstraints="tangential residual and bounded error",score="error - representation complexity",candidateCount=2*coarsening.MergedPairCount,winner="per admitted merge"}},exactAlgorithms=new[]{"Edmonds blossom for maximum-cardinality layout","Edmonds blossom for disjoint merge selection"},notJudgment=new[]{"manifoldness","boundary-loop count","seam incidence","foldover legality"} });
timings["diagnosticsAggregationAndSerialization"] = Lap(); timings["total"] = total.Elapsed.TotalMilliseconds; Write("performance.json",new{timingsMilliseconds=timings,workingSetBytes=Environment.WorkingSet});
var success = false; Write("validation-report.json",new{milestone="AETHERIS-BUNNY-M3",status="MeaningfulProgression",source=sourceValidation,globalPairAtlas=new{panels=atlas.Charts.Count,transitions=atlas.UnresolvedTriangles.Count,cracks=canonical.InternalCrackGroups,loops=canonical.IntentionalOpenBoundaryLoops,nonManifold=canonical.NonManifoldEdgeCount,valid=canonical.ValidationStatus},nativeBoundedPatchPlaneProxyClosed=canonical.Document.Patches.Where(x=>x.ChartId?.StartsWith("quad-")==true).All(x=>x.Support.Kind==Aetheris.Kernel.Core.Brep.Tessellation.SurfaceMeshSupportKind.BoundedParametricPatch),residualAuthorityFixtures=true,coarsenedAtlas=new{panels=coarsening.Panels.Count,globallyLowered=false},success,nextBlocker="general multi-Panel chart parameterization and authoritative shared residual-boundary construction; the current bounded pair coarsener cannot yet replace the globally valid pair atlas"});
File.WriteAllText(Path.Combine(output,"README.md"),"""
# AETHERIS-BUNNY-M3 evidence

M3 separates structural `PanelIr` support from sampled scalar offset and differential-only normal fields, replaces the SurfaceMeshIR plane proxy with a native bounded parametric evaluator, and replaces M2's local matching with deterministic Edmonds blossom matching.

The canonical run is **Meaningful Progression**, not Success. The global pair atlas is crack-free and has one parity-forced transition. The bounded coarsener demonstrates fewer structural Panels and residual representation on admitted two-Panel unions, but those unions are not yet installed as the canonical atlas because arbitrary multi-chart parameterization and globally authoritative residual seam construction remain unresolved.

Reproduce with `dotnet run --project tools/Aetheris.BunnyM3 -c Release -- .tmp/bunny-m0-source/bunny/reconstruction/bun_zipper.ply artifacts/local/evidence/geometry/bunny-m3`.
""");
var files=Directory.GetFiles(output).Where(x=>Path.GetFileName(x)!="manifest.json"&&Path.GetFileName(x)!="performance.json").OrderBy(Path.GetFileName,StringComparer.Ordinal).Select(x=>new{path=Path.GetFileName(x),sha256=Sha(File.ReadAllBytes(x)),bytes=new FileInfo(x).Length,lines=File.ReadLines(x).Count()}).ToArray();
Write("manifest.json",new{milestone="AETHERIS-BUNNY-M3",sourceMeshHash=mesh.DeterministicHash,atlasHash=atlas.DeterministicHash,surfaceMeshHash=canonical.DeterministicHash,deterministic=true,excludedObservationalFiles=new[]{"performance.json"},files});
Console.WriteLine(JsonSerializer.Serialize(new{status="MeaningfulProgression",atlasPanels=atlas.Charts.Count,structuralCandidates=coarsening.Panels.Count,residualMapped=mapped.Length,transitions=atlas.UnresolvedTriangles.Count,singularities=regularization.OutputSingularities,loops=canonical.IntentionalOpenBoundaryLoops,cracks=canonical.InternalCrackGroups,nonManifold=canonical.NonManifoldEdgeCount,totalMilliseconds=total.Elapsed.TotalMilliseconds}));

double Lap(){var value=watch.Elapsed.TotalMilliseconds;watch.Restart();return value;} void Write(string name,object value)=>File.WriteAllText(Path.Combine(output,name),JsonSerializer.Serialize(value,new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase,IncludeFields=true}));
static double Mean(IEnumerable<double> values){var a=values.ToArray();return a.Length==0?0:a.Average();} static double Rms(IEnumerable<double> values){var a=values.ToArray();return a.Length==0?0:Math.Sqrt(a.Average(x=>x*x));} static double Max(IEnumerable<double> values)=>values.DefaultIfEmpty(0).Max(); static double P(IEnumerable<double> values,double p){var a=values.Order().ToArray();return a.Length==0?0:a[(int)Math.Clamp(Math.Ceiling(p*a.Length)-1,0,a.Length-1)];}
static IEnumerable<double> GridValues(BilinearScalarField field){for(var i=0;i<field.CountU;i++)for(var j=0;j<field.CountV;j++)yield return field[i,j];} static string Sha(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
static string FindRoot(){var directory=new DirectoryInfo(AppContext.BaseDirectory);while(directory is not null&&!File.Exists(Path.Combine(directory.FullName,"Aetheris.slnx")))directory=directory.Parent;return directory?.FullName??Directory.GetCurrentDirectory();}
