<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aetheris.Kernel.Core" Version="2.0.0-preview.2" />
    <PackageReference Include="Aetheris.Kernel.Firmament" Version="2.0.0-preview.2" />
    <PackageReference Include="Aetheris.Forge.Host" Version="2.0.0-preview.2" />
    <PackageReference Include="Aetheris.Forge.KernelSDK" Version="2.0.0-preview.2" />
  </ItemGroup>
</Project>
