using Aetheris.Kernel.Core.Math;
using Aetheris.Kernel.Core.Step242;
using Aetheris.Kernel.Firmament.FirmamentV2;
using Aetheris.Kernel.Firmament.Piping;

namespace Aetheris.Kernel.Firmament.Tests;

public sealed class PipingX3Tests
{
    private static readonly string Root=FindRoot();

    [Theory]
    [InlineData("pipe-segment.firmament")]
    [InlineData("elbow90.firmament")]
    [InlineData("explicit-route.firmament")]
    [InlineData("route-around-keepout.firmament")]
    [InlineData("autorouted-connection.firmament")]
    [InlineData("local-reroute.firmament")]
    [InlineData("pump-skid.firmament")]
    public void CanonicalPipingFixtures_CompileAndReimportAsAssembly(string file)
    {
        var path=Path.Combine(Root,"fixtures","Canonical","Piping",file);
        var result=PipingAuthoring.Compile(File.ReadAllText(path),path);
        Assert.True(result.IsSuccess,string.Join(Environment.NewLine,result.Diagnostics));
        Assert.NotNull(result.Report);Assert.NotEmpty(result.Report.Routes);Assert.NotEmpty(result.Report.PipeSegments);
        Assert.True(result.Report.ComponentsEnclosed);Assert.True(result.Report.GeometryClearanceVerified);
        var imported=Step242AssemblyImporter.Import(result.StepText!);
        Assert.True(imported.IsSuccess,string.Join(Environment.NewLine,imported.Diagnostics.Select(x=>x.Message)));
        Assert.Equal(result.Report.BodyCount,imported.Value.Definitions.Count(x=>x.Geometry is not null));
    }

    [Fact]
    public void Autoroute_IsDeterministicInspectable_AndAcceptanceCreatesOrdinaryRouteAuthority()
    {
        var path=Path.Combine(Root,"fixtures","Canonical","Piping","autorouted-connection.firmament");var source=File.ReadAllText(path);
        var first=PipingAuthoring.Compile(source,path);var second=PipingAuthoring.Compile(source,path);
        Assert.True(first.IsSuccess&&second.IsSuccess,string.Join(Environment.NewLine,first.Diagnostics.Concat(second.Diagnostics)));
        Assert.Equal(first.StepText,second.StepText);Assert.Equal(PipingAuthoring.RoutingJson(first.Report!),PipingAuthoring.RoutingJson(second.Report!));
        var proposal=Assert.Single(first.Report!.RouteProposals);Assert.True(proposal.IsSuccess);Assert.True(proposal.MinimumClearanceMm>=30);
        var route=Assert.Single(first.Report.Routes);Assert.Equal(RouteProvenance.AutoGenerated,route.Provenance);
        Assert.StartsWith("accepted:proposal:",route.SourceProvenance,StringComparison.Ordinal);
        Assert.NotEmpty(route.Anchors);Assert.DoesNotContain("Request",route.StableId,StringComparison.Ordinal);
    }

    [Fact]
    public void MaterializedClearance_CatchesElbowEnvelopeThatSharpPolylineMisses()
    {
        var obstacle=new KeepOutIr("keepout:test","Frame",new(0,0,-10),new(100,100,10),"StructureMember");
        Point3D[] points=[new(-100,-42.5,0),new(142.5,-42.5,0),new(142.5,200,0)];
        var sharp=OrthogonalAutoRouter.MinimumClearance(points,[obstacle],12.5);
        var realized=OrthogonalAutoRouter.MinimumMaterializedClearance(points,[obstacle],12.5,50);
        Assert.Equal(30,sharp,6);
        Assert.True(realized<30,$"Expected the torus envelope to reduce clearance below 30 mm; measured {realized:G6} mm.");
    }

    [Fact]
    public void EquipmentNozzles_AreOwnedMatedContinuous_AndOnlyExemptTheirOwnKeepOut()
    {
        var path=Path.Combine(Root,"fixtures","Canonical","Piping","pump-skid.firmament");var result=PipingAuthoring.Compile(File.ReadAllText(path),path);
        Assert.True(result.IsSuccess,string.Join(Environment.NewLine,result.Diagnostics));var report=result.Report!;
        Assert.Equal("aetheris:piping:x3a",report.Schema);Assert.Equal(2,report.Equipment.Count);Assert.Equal(4,report.Nozzles.Count);Assert.Equal(4,report.Mates.Count);Assert.Equal(4,report.KeepOutExemptions.Count);
        Assert.All(report.Mates,m=>{Assert.True(m.Coincident);Assert.True(m.DirectionsOpposed);Assert.Equal(m.Position,report.Ports.Single(p=>p.Name==m.Port).Position);});
        Assert.All(report.KeepOutExemptions,e=>Assert.Equal("NozzleEnvelopeOnly",e.Scope));
        foreach(var nozzle in report.Nozzles)
        {
            var port=report.Ports.Single(x=>x.Name==nozzle.Port);var owner=report.KeepOuts.Single(x=>x.Name==nozzle.OwnerKeepOut);var policy=report.PipePolicies.Single(x=>x.StableId==nozzle.PipePolicy);
            Assert.Equal(port.Position,nozzle.TipPosition);Assert.Equal(port.NozzleLengthMm,(nozzle.TipPosition-nozzle.RootPosition).Length,6);
            Assert.Equal(0,OrthogonalAutoRouter.MinimumClearance([nozzle.RootPosition,nozzle.TipPosition],[owner],policy.RadiusMm),6);
            var foreign=report.KeepOuts.Where(x=>x.Name!=owner.Name).ToArray();Assert.True(OrthogonalAutoRouter.MinimumClearance([nozzle.RootPosition,nozzle.TipPosition],foreign,policy.RadiusMm)>=30);
        }
        Assert.True(report.GeometryClearanceVerified);Assert.True(report.MinimumVerifiedClearanceMm>=30);
    }

    [Fact]
    public void LocalReroute_PreservesSuffixAndLockOutsideAuthorizedInterval()
    {
        var path=Path.Combine(Root,"fixtures","Canonical","Piping","local-reroute.firmament");var result=PipingAuthoring.Compile(File.ReadAllText(path),path);
        Assert.True(result.IsSuccess,string.Join(Environment.NewLine,result.Diagnostics));var route=Assert.Single(result.Report!.Routes);
        Assert.Equal(RouteProvenance.LocallyRerouted,route.Provenance);
        Assert.Equal(new Point3D(500,300,300),route.Anchors[^2].Point);
        Assert.Equal(new Point3D(1000,300,300),route.Anchors[^1].Point);
        var locked=Assert.Single(route.Segments,x=>x.Locked);
        Assert.Equal(new Point3D(500,300,0),route.Anchors[locked.Ordinal].Point);
        Assert.Equal(new Point3D(500,300,300),route.Anchors[locked.Ordinal+1].Point);
    }

    [Theory]
    [InlineData("pipe-wall-too-thick.firmament","piping-pipe-wall-too-thick")]
    [InlineData("incompatible-port.firmament","piping-incompatible-port")]
    [InlineData("route-through-keepout.firmament","piping-route-through-keepout")]
    [InlineData("insufficient-clearance.firmament","piping-insufficient-clearance")]
    [InlineData("unreachable-hard-waypoint.firmament","piping-autoroute-hard-waypoint-unreachable")]
    [InlineData("autoroute-no-solution.firmament","piping-autoroute-endpoint-direction-impossible")]
    [InlineData("local-reroute-crosses-lock.firmament","piping-local-reroute-crosses-lock")]
    [InlineData("nozzle-root-off-owner-face.firmament","piping-nozzle-root-not-on-owner-face")]
    [InlineData("nozzle-crosses-foreign-keepout.firmament","piping-nozzle-foreign-keepout-clearance")]
    public void InvalidPipingFixtures_IsolateDiagnostic(string file,string code)
    {
        var path=Path.Combine(Root,"fixtures","Invalid","Piping",file);var result=PipingAuthoring.Compile(File.ReadAllText(path),path);
        Assert.False(result.IsSuccess);Assert.Contains(result.Diagnostics,x=>x.Contains(code,StringComparison.Ordinal));
    }

    [Fact]
    public void StandardPipingLibrary_ResolvesGenericProducts()
    {
        const string source="""
            Use Standard.Piping
            Model LibraryWitness {
                Units: mm
                Let Pipe = Standard.Piping.Pipe
                Let Elbow = Standard.Piping.Elbow90
                Let Tee = Standard.Piping.Tee
            }
            """;
        var resolved=FirmamentStandardLibraryResolver.Resolve(source,out var diagnostics);
        Assert.NotNull(resolved);Assert.Empty(diagnostics);
        Assert.Contains("Struct PipeTemplate",resolved.Source,StringComparison.Ordinal);
        Assert.Contains("Struct Elbow90Template",resolved.Source,StringComparison.Ordinal);
        Assert.Contains("Struct TeeTemplate",resolved.Source,StringComparison.Ordinal);
    }

    private static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null&&!File.Exists(Path.Combine(d.FullName,"Aetheris.slnx")))d=d.Parent;return d?.FullName??throw new DirectoryNotFoundException();}
}
