// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    public static class MaterialCatalogMetadataEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(MaterialCatalogMetadataEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CatalogId>k__BackingField")]
        public static extern ref string CatalogId(MaterialCatalogMetadataEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SchemaVersion>k__BackingField")]
        public static extern ref int SchemaVersion(MaterialCatalogMetadataEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SeedVersion>k__BackingField")]
        public static extern ref string SeedVersion(MaterialCatalogMetadataEntity @this);
    }
}
