// <auto-generated />
using Aetheris.Kernel.StandardLibrary.Materials.Database;
using Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MaterialCatalogDbContext), typeof(MaterialCatalogDbContextModel))]
