// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class MaterialPropertyEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity",
                typeof(MaterialPropertyEntity),
                baseEntityType,
                propertyCount: 11,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Id(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, int value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, int value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && MaterialPropertyEntityUnsafeAccessors.Id(((MaterialPropertyEntity)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : MaterialPropertyEntityUnsafeAccessors.Id(((MaterialPropertyEntity)(entry.Entity))))),
                int (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Id(((MaterialPropertyEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var authority = runtimeEntityType.AddProperty(
                "Authority",
                typeof(MaterialPropertyAuthority),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Authority", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Authority>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            authority.SetGetter(
                MaterialPropertyAuthority (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Authority(instance),
                bool (MaterialPropertyEntity instance) => object.Equals(((object)(MaterialPropertyEntityUnsafeAccessors.Authority(instance))), ((object)(MaterialPropertyAuthority.ManufacturerTypical))));
            authority.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialPropertyAuthority value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Authority(instance) = value;
                    return instance;
                });
            authority.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialPropertyAuthority value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Authority(instance) = value;
                    return instance;
                });
            authority.SetAccessors(
                MaterialPropertyAuthority (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Authority(((MaterialPropertyEntity)(entry.Entity))),
                MaterialPropertyAuthority (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Authority(((MaterialPropertyEntity)(entry.Entity))),
                MaterialPropertyAuthority (IInternalEntry entry) => entry.ReadOriginalValue<MaterialPropertyAuthority>(authority, 1),
                MaterialPropertyAuthority (IInternalEntry entry) => entry.GetCurrentValue<MaterialPropertyAuthority>(authority));
            authority.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            authority.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<MaterialPropertyAuthority>(
                    bool (MaterialPropertyAuthority v1, MaterialPropertyAuthority v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (MaterialPropertyAuthority v) => ((object)v).GetHashCode(),
                    MaterialPropertyAuthority (MaterialPropertyAuthority v) => v),
                keyComparer: new ValueComparer<MaterialPropertyAuthority>(
                    bool (MaterialPropertyAuthority v1, MaterialPropertyAuthority v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (MaterialPropertyAuthority v) => ((object)v).GetHashCode(),
                    MaterialPropertyAuthority (MaterialPropertyAuthority v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<MaterialPropertyAuthority, string>(
                    string (MaterialPropertyAuthority v) => ((object)v).ToString(),
                    MaterialPropertyAuthority (string v) => StringEnumConverter<MaterialPropertyAuthority, string, MaterialPropertyAuthority>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<MaterialPropertyAuthority, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<MaterialPropertyAuthority, string>(
                        string (MaterialPropertyAuthority v) => ((object)v).ToString(),
                        MaterialPropertyAuthority (string v) => StringEnumConverter<MaterialPropertyAuthority, string, MaterialPropertyAuthority>.ConvertToEnum(v))));
            authority.SetSentinelFromProviderValue("ManufacturerTypical");

            var condition = runtimeEntityType.AddProperty(
                "Condition",
                typeof(string),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Condition", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Condition>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            condition.SetGetter(
                string (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Condition(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Condition(instance) == null);
            condition.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Condition(instance) = value;
                    return instance;
                });
            condition.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Condition(instance) = value;
                    return instance;
                });
            condition.SetAccessors(
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Condition(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Condition(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(condition, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(condition));
            condition.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            condition.TypeMapping = SqliteStringTypeMapping.Default;

            var kind = runtimeEntityType.AddProperty(
                "Kind",
                typeof(MaterialPropertyKind),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Kind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Kind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            kind.SetGetter(
                MaterialPropertyKind (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Kind(instance),
                bool (MaterialPropertyEntity instance) => object.Equals(((object)(MaterialPropertyEntityUnsafeAccessors.Kind(instance))), ((object)(MaterialPropertyKind.Density))));
            kind.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialPropertyKind value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Kind(instance) = value;
                    return instance;
                });
            kind.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialPropertyKind value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Kind(instance) = value;
                    return instance;
                });
            kind.SetAccessors(
                MaterialPropertyKind (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Kind(((MaterialPropertyEntity)(entry.Entity))),
                MaterialPropertyKind (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Kind(((MaterialPropertyEntity)(entry.Entity))),
                MaterialPropertyKind (IInternalEntry entry) => entry.ReadOriginalValue<MaterialPropertyKind>(kind, 3),
                MaterialPropertyKind (IInternalEntry entry) => entry.GetCurrentValue<MaterialPropertyKind>(kind));
            kind.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            kind.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<MaterialPropertyKind>(
                    bool (MaterialPropertyKind v1, MaterialPropertyKind v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (MaterialPropertyKind v) => ((object)v).GetHashCode(),
                    MaterialPropertyKind (MaterialPropertyKind v) => v),
                keyComparer: new ValueComparer<MaterialPropertyKind>(
                    bool (MaterialPropertyKind v1, MaterialPropertyKind v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (MaterialPropertyKind v) => ((object)v).GetHashCode(),
                    MaterialPropertyKind (MaterialPropertyKind v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<MaterialPropertyKind, string>(
                    string (MaterialPropertyKind v) => ((object)v).ToString(),
                    MaterialPropertyKind (string v) => StringEnumConverter<MaterialPropertyKind, string, MaterialPropertyKind>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<MaterialPropertyKind, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<MaterialPropertyKind, string>(
                        string (MaterialPropertyKind v) => ((object)v).ToString(),
                        MaterialPropertyKind (string v) => StringEnumConverter<MaterialPropertyKind, string, MaterialPropertyKind>.ConvertToEnum(v))));
            kind.SetCurrentValueComparer(new EntryCurrentValueComparer<MaterialPropertyKind>(kind));
            kind.SetSentinelFromProviderValue("Density");

            var materialId = runtimeEntityType.AddProperty(
                "MaterialId",
                typeof(int),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("MaterialId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<MaterialId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            materialId.SetGetter(
                int (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.MaterialId(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.MaterialId(instance) == 0);
            materialId.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, int value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.MaterialId(instance) = value;
                    return instance;
                });
            materialId.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, int value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.MaterialId(instance) = value;
                    return instance;
                });
            materialId.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(4) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(4) && MaterialPropertyEntityUnsafeAccessors.MaterialId(((MaterialPropertyEntity)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(1) : MaterialPropertyEntityUnsafeAccessors.MaterialId(((MaterialPropertyEntity)(entry.Entity))))),
                int (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.MaterialId(((MaterialPropertyEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(materialId, 4),
                int (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<int>(materialId, 1));
            materialId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            materialId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            materialId.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(materialId));

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            notes.SetGetter(
                string (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Notes(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Notes(instance) == null);
            notes.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Notes(instance) = value;
                    return instance;
                });
            notes.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Notes(instance) = value;
                    return instance;
                });
            notes.SetAccessors(
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Notes(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Notes(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(notes, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(notes));
            notes.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            notes.TypeMapping = SqliteStringTypeMapping.Default;

            var referenceTemperatureKelvin = runtimeEntityType.AddProperty(
                "ReferenceTemperatureKelvin",
                typeof(double?),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("ReferenceTemperatureKelvin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<ReferenceTemperatureKelvin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            referenceTemperatureKelvin.SetGetter(
                double? (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(instance),
                bool (MaterialPropertyEntity instance) => !(MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(instance).HasValue));
            referenceTemperatureKelvin.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, double? value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(instance) = value;
                    return instance;
                });
            referenceTemperatureKelvin.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, double? value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(instance) = value;
                    return instance;
                });
            referenceTemperatureKelvin.SetAccessors(
                double? (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(((MaterialPropertyEntity)(entry.Entity))),
                double? (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.ReferenceTemperatureKelvin(((MaterialPropertyEntity)(entry.Entity))),
                double? (IInternalEntry entry) => entry.ReadOriginalValue<double?>(referenceTemperatureKelvin, 6),
                double? (IInternalEntry entry) => entry.GetCurrentValue<double?>(referenceTemperatureKelvin));
            referenceTemperatureKelvin.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            referenceTemperatureKelvin.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                keyComparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));
            referenceTemperatureKelvin.SetComparer(new NullableValueComparer<double>(referenceTemperatureKelvin.TypeMapping.Comparer));
            referenceTemperatureKelvin.SetKeyComparer(new NullableValueComparer<double>(referenceTemperatureKelvin.TypeMapping.KeyComparer));

            var sourceId = runtimeEntityType.AddProperty(
                "SourceId",
                typeof(string),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("SourceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<SourceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sourceId.SetGetter(
                string (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.SourceId(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.SourceId(instance) == null);
            sourceId.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.SourceId(instance) = value;
                    return instance;
                });
            sourceId.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.SourceId(instance) = value;
                    return instance;
                });
            sourceId.SetAccessors(
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.SourceId(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.SourceId(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(sourceId, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(sourceId));
            sourceId.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            sourceId.TypeMapping = SqliteStringTypeMapping.Default;

            var sourceUri = runtimeEntityType.AddProperty(
                "SourceUri",
                typeof(string),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("SourceUri", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<SourceUri>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sourceUri.SetGetter(
                string (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.SourceUri(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.SourceUri(instance) == null);
            sourceUri.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.SourceUri(instance) = value;
                    return instance;
                });
            sourceUri.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.SourceUri(instance) = value;
                    return instance;
                });
            sourceUri.SetAccessors(
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.SourceUri(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.SourceUri(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(sourceUri, 8),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(sourceUri));
            sourceUri.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            sourceUri.TypeMapping = SqliteStringTypeMapping.Default;

            var unitSymbol = runtimeEntityType.AddProperty(
                "UnitSymbol",
                typeof(string),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("UnitSymbol", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<UnitSymbol>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            unitSymbol.SetGetter(
                string (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.UnitSymbol(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.UnitSymbol(instance) == null);
            unitSymbol.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.UnitSymbol(instance) = value;
                    return instance;
                });
            unitSymbol.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, string value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.UnitSymbol(instance) = value;
                    return instance;
                });
            unitSymbol.SetAccessors(
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.UnitSymbol(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.UnitSymbol(((MaterialPropertyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(unitSymbol, 9),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(unitSymbol));
            unitSymbol.SetPropertyIndexes(
                index: 9,
                originalValueIndex: 9,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            unitSymbol.TypeMapping = SqliteStringTypeMapping.Default;

            var valueSi = runtimeEntityType.AddProperty(
                "ValueSi",
                typeof(double),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("ValueSi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<ValueSi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            valueSi.SetGetter(
                double (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.ValueSi(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.ValueSi(instance).Equals(0D));
            valueSi.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, double value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.ValueSi(instance) = value;
                    return instance;
                });
            valueSi.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, double value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.ValueSi(instance) = value;
                    return instance;
                });
            valueSi.SetAccessors(
                double (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.ValueSi(((MaterialPropertyEntity)(entry.Entity))),
                double (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.ValueSi(((MaterialPropertyEntity)(entry.Entity))),
                double (IInternalEntry entry) => entry.ReadOriginalValue<double>(valueSi, 10),
                double (IInternalEntry entry) => entry.GetCurrentValue<double>(valueSi));
            valueSi.SetPropertyIndexes(
                index: 10,
                originalValueIndex: 10,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            valueSi.TypeMapping = DoubleTypeMapping.Default.Clone(
                comparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                keyComparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                providerValueComparer: new ValueComparer<double>(
                    bool (double v1, double v2) => v1.Equals(v2),
                    int (double v) => ((object)v).GetHashCode(),
                    double (double v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "REAL"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { materialId, kind },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MaterialId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var material = declaringEntityType.AddNavigation("Material",
                runtimeForeignKey,
                onDependent: true,
                typeof(MaterialEntity),
                propertyInfo: typeof(MaterialPropertyEntity).GetProperty("Material", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialPropertyEntity).GetField("<Material>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            material.SetGetter(
                MaterialEntity (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Material(instance),
                bool (MaterialPropertyEntity instance) => MaterialPropertyEntityUnsafeAccessors.Material(instance) == null);
            material.SetSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialEntity value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Material(instance) = value;
                    return instance;
                });
            material.SetMaterializationSetter(
                MaterialPropertyEntity (MaterialPropertyEntity instance, MaterialEntity value) =>
                {
                    MaterialPropertyEntityUnsafeAccessors.Material(instance) = value;
                    return instance;
                });
            material.SetAccessors(
                MaterialEntity (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Material(((MaterialPropertyEntity)(entry.Entity))),
                MaterialEntity (IInternalEntry entry) => MaterialPropertyEntityUnsafeAccessors.Material(((MaterialPropertyEntity)(entry.Entity))),
                null,
                MaterialEntity (IInternalEntry entry) => entry.GetCurrentValue<MaterialEntity>(material));
            material.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            var properties = principalEntityType.AddNavigation("Properties",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<MaterialPropertyEntity>),
                propertyInfo: typeof(MaterialEntity).GetProperty("Properties", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialEntity).GetField("<Properties>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            properties.SetGetter(
                ICollection<MaterialPropertyEntity> (MaterialEntity instance) => MaterialEntityUnsafeAccessors.Properties(instance),
                bool (MaterialEntity instance) => MaterialEntityUnsafeAccessors.Properties(instance) == null);
            properties.SetSetter(
                MaterialEntity (MaterialEntity instance, ICollection<MaterialPropertyEntity> value) =>
                {
                    MaterialEntityUnsafeAccessors.Properties(instance) = value;
                    return instance;
                });
            properties.SetMaterializationSetter(
                MaterialEntity (MaterialEntity instance, ICollection<MaterialPropertyEntity> value) =>
                {
                    MaterialEntityUnsafeAccessors.Properties(instance) = value;
                    return instance;
                });
            properties.SetAccessors(
                ICollection<MaterialPropertyEntity> (IInternalEntry entry) => MaterialEntityUnsafeAccessors.Properties(((MaterialEntity)(entry.Entity))),
                ICollection<MaterialPropertyEntity> (IInternalEntry entry) => MaterialEntityUnsafeAccessors.Properties(((MaterialEntity)(entry.Entity))),
                null,
                ICollection<MaterialPropertyEntity> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<MaterialPropertyEntity>>(properties));
            properties.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            properties.SetCollectionAccessor<MaterialEntity, ICollection<MaterialPropertyEntity>, MaterialPropertyEntity>(
                ICollection<MaterialPropertyEntity> (MaterialEntity entity) => MaterialEntityUnsafeAccessors.Properties(entity),
                (MaterialEntity entity, ICollection<MaterialPropertyEntity> collection) => MaterialEntityUnsafeAccessors.Properties(entity) = ((ICollection<MaterialPropertyEntity>)(collection)),
                (MaterialEntity entity, ICollection<MaterialPropertyEntity> collection) => MaterialEntityUnsafeAccessors.Properties(entity) = ((ICollection<MaterialPropertyEntity>)(collection)),
                ICollection<MaterialPropertyEntity> (MaterialEntity entity, Action<MaterialEntity, ICollection<MaterialPropertyEntity>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<MaterialEntity, ICollection<MaterialPropertyEntity>, MaterialPropertyEntity>(entity, setter),
                ICollection<MaterialPropertyEntity> () => ((ICollection<MaterialPropertyEntity>)(((ICollection<MaterialPropertyEntity>)(new HashSet<MaterialPropertyEntity>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var authority = runtimeEntityType.FindProperty("Authority");
            var condition = runtimeEntityType.FindProperty("Condition");
            var kind = runtimeEntityType.FindProperty("Kind");
            var materialId = runtimeEntityType.FindProperty("MaterialId");
            var notes = runtimeEntityType.FindProperty("Notes");
            var referenceTemperatureKelvin = runtimeEntityType.FindProperty("ReferenceTemperatureKelvin");
            var sourceId = runtimeEntityType.FindProperty("SourceId");
            var sourceUri = runtimeEntityType.FindProperty("SourceUri");
            var unitSymbol = runtimeEntityType.FindProperty("UnitSymbol");
            var valueSi = runtimeEntityType.FindProperty("ValueSi");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            var material = runtimeEntityType.FindNavigation("Material");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MaterialPropertyEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, MaterialPropertyAuthority, string, MaterialPropertyKind, int, string, double?, string, string, string, double>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<MaterialPropertyAuthority>)(((IProperty)authority).GetValueComparer())).Snapshot(source.GetCurrentValue<MaterialPropertyAuthority>(authority)), (source.GetCurrentValue<string>(condition) == null ? null : ((ValueComparer<string>)(((IProperty)condition).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(condition))), ((ValueComparer<MaterialPropertyKind>)(((IProperty)kind).GetValueComparer())).Snapshot(source.GetCurrentValue<MaterialPropertyKind>(kind)), ((ValueComparer<int>)(((IProperty)materialId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(materialId)), (source.GetCurrentValue<string>(notes) == null ? null : ((ValueComparer<string>)(((IProperty)notes).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(notes))), (source.GetCurrentValue<double?>(referenceTemperatureKelvin) == null ? null : ((ValueComparer<double?>)(((IProperty)referenceTemperatureKelvin).GetValueComparer())).Snapshot(source.GetCurrentValue<double?>(referenceTemperatureKelvin))), (source.GetCurrentValue<string>(sourceId) == null ? null : ((ValueComparer<string>)(((IProperty)sourceId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(sourceId))), (source.GetCurrentValue<string>(sourceUri) == null ? null : ((ValueComparer<string>)(((IProperty)sourceUri).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(sourceUri))), (source.GetCurrentValue<string>(unitSymbol) == null ? null : ((ValueComparer<string>)(((IProperty)unitSymbol).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(unitSymbol))), ((ValueComparer<double>)(((IProperty)valueSi).GetValueComparer())).Snapshot(source.GetCurrentValue<double>(valueSi)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<int>)(((IProperty)materialId).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, int>(default(int), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MaterialPropertyEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int, object>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)materialId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(materialId)), source.GetCurrentValue<MaterialEntity>(material))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 11,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 11,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MaterialProperties");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
