// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    public static class MaterialEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CatalogId>k__BackingField")]
        public static extern ref string CatalogId(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConstitutiveClass>k__BackingField")]
        public static extern ref MaterialConstitutiveClass ConstitutiveClass(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Designation>k__BackingField")]
        public static extern ref string Designation(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DisplayName>k__BackingField")]
        public static extern ref string DisplayName(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Family>k__BackingField")]
        public static extern ref string Family(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FirmamentPath>k__BackingField")]
        public static extern ref string FirmamentPath(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Grade>k__BackingField")]
        public static extern ref string Grade(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReferenceCondition>k__BackingField")]
        public static extern ref string ReferenceCondition(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StableId>k__BackingField")]
        public static extern ref string StableId(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Standard>k__BackingField")]
        public static extern ref string Standard(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Temper>k__BackingField")]
        public static extern ref string Temper(MaterialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Properties>k__BackingField")]
        public static extern ref ICollection<MaterialPropertyEntity> Properties(MaterialEntity @this);
    }
}
