// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class MaterialCatalogMetadataEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity",
                typeof(MaterialCatalogMetadataEntity),
                baseEntityType,
                propertyCount: 4,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(MaterialCatalogMetadataEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialCatalogMetadataEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.Id(instance),
                bool (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, int value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, int value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && MaterialCatalogMetadataEntityUnsafeAccessors.Id(((MaterialCatalogMetadataEntity)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : MaterialCatalogMetadataEntityUnsafeAccessors.Id(((MaterialCatalogMetadataEntity)(entry.Entity))))),
                int (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.Id(((MaterialCatalogMetadataEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var catalogId = runtimeEntityType.AddProperty(
                "CatalogId",
                typeof(string),
                propertyInfo: typeof(MaterialCatalogMetadataEntity).GetProperty("CatalogId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialCatalogMetadataEntity).GetField("<CatalogId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            catalogId.SetGetter(
                string (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(instance),
                bool (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(instance) == null);
            catalogId.SetSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, string value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(instance) = value;
                    return instance;
                });
            catalogId.SetMaterializationSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, string value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(instance) = value;
                    return instance;
                });
            catalogId.SetAccessors(
                string (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(((MaterialCatalogMetadataEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.CatalogId(((MaterialCatalogMetadataEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(catalogId, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(catalogId));
            catalogId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            catalogId.TypeMapping = SqliteStringTypeMapping.Default;
            catalogId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(catalogId));

            var schemaVersion = runtimeEntityType.AddProperty(
                "SchemaVersion",
                typeof(int),
                propertyInfo: typeof(MaterialCatalogMetadataEntity).GetProperty("SchemaVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialCatalogMetadataEntity).GetField("<SchemaVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            schemaVersion.SetGetter(
                int (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(instance),
                bool (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(instance) == 0);
            schemaVersion.SetSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, int value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(instance) = value;
                    return instance;
                });
            schemaVersion.SetMaterializationSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, int value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(instance) = value;
                    return instance;
                });
            schemaVersion.SetAccessors(
                int (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(((MaterialCatalogMetadataEntity)(entry.Entity))),
                int (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.SchemaVersion(((MaterialCatalogMetadataEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(schemaVersion, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(schemaVersion));
            schemaVersion.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            schemaVersion.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var seedVersion = runtimeEntityType.AddProperty(
                "SeedVersion",
                typeof(string),
                propertyInfo: typeof(MaterialCatalogMetadataEntity).GetProperty("SeedVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaterialCatalogMetadataEntity).GetField("<SeedVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            seedVersion.SetGetter(
                string (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(instance),
                bool (MaterialCatalogMetadataEntity instance) => MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(instance) == null);
            seedVersion.SetSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, string value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(instance) = value;
                    return instance;
                });
            seedVersion.SetMaterializationSetter(
                MaterialCatalogMetadataEntity (MaterialCatalogMetadataEntity instance, string value) =>
                {
                    MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(instance) = value;
                    return instance;
                });
            seedVersion.SetAccessors(
                string (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(((MaterialCatalogMetadataEntity)(entry.Entity))),
                string (IInternalEntry entry) => MaterialCatalogMetadataEntityUnsafeAccessors.SeedVersion(((MaterialCatalogMetadataEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(seedVersion, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(seedVersion));
            seedVersion.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            seedVersion.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { catalogId },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var catalogId = runtimeEntityType.FindProperty("CatalogId");
            var schemaVersion = runtimeEntityType.FindProperty("SchemaVersion");
            var seedVersion = runtimeEntityType.FindProperty("SeedVersion");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MaterialCatalogMetadataEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(catalogId) == null ? null : ((ValueComparer<string>)(((IProperty)catalogId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(catalogId))), ((ValueComparer<int>)(((IProperty)schemaVersion).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(schemaVersion)), (source.GetCurrentValue<string>(seedVersion) == null ? null : ((ValueComparer<string>)(((IProperty)seedVersion).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(seedVersion))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MaterialCatalogMetadataEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CatalogMetadata");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
