// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    public partial class MaterialCatalogDbContextModel
    {
        private MaterialCatalogDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cbbcdd26-01c9-4e7c-a044-a673db089200"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var materialCatalogMetadataEntity = MaterialCatalogMetadataEntityEntityType.Create(this);
            var materialEntity = MaterialEntityEntityType.Create(this);
            var materialPropertyEntity = MaterialPropertyEntityEntityType.Create(this);

            MaterialPropertyEntityEntityType.CreateForeignKey1(materialPropertyEntity, materialEntity);

            MaterialCatalogMetadataEntityEntityType.CreateAnnotations(materialCatalogMetadataEntity);
            MaterialEntityEntityType.CreateAnnotations(materialEntity);
            MaterialPropertyEntityEntityType.CreateAnnotations(materialPropertyEntity);

            AddAnnotation("ProductVersion", "10.0.0");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var materialCatalogMetadataEntity = FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            materialCatalogMetadataEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase = new TableBase("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity", null, relationalModel);
            var catalogIdColumnBase = new ColumnBase<ColumnMappingBase>("CatalogId", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase.Columns.Add("CatalogId", catalogIdColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase.Columns.Add("Id", idColumnBase);
            var schemaVersionColumnBase = new ColumnBase<ColumnMappingBase>("SchemaVersion", "INTEGER", aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase.Columns.Add("SchemaVersion", schemaVersionColumnBase);
            var seedVersionColumnBase = new ColumnBase<ColumnMappingBase>("SeedVersion", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase.Columns.Add("SeedVersion", seedVersionColumnBase);
            relationalModel.DefaultTables.Add("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity", aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase = new TableMappingBase<ColumnMappingBase>(materialCatalogMetadataEntity, aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase, null);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityTableBase.AddTypeMapping(aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase, false);
            defaultTableMappings.Add(aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, materialCatalogMetadataEntity.FindProperty("Id")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)catalogIdColumnBase, materialCatalogMetadataEntity.FindProperty("CatalogId")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)schemaVersionColumnBase, materialCatalogMetadataEntity.FindProperty("SchemaVersion")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)seedVersionColumnBase, materialCatalogMetadataEntity.FindProperty("SeedVersion")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialCatalogMetadataEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            materialCatalogMetadataEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var catalogMetadataTable = new Table("CatalogMetadata", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", catalogMetadataTable);
            catalogMetadataTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var catalogIdColumn = new Column("CatalogId", "TEXT", catalogMetadataTable);
            catalogMetadataTable.Columns.Add("CatalogId", catalogIdColumn);
            catalogIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(catalogIdColumn);
            var schemaVersionColumn = new Column("SchemaVersion", "INTEGER", catalogMetadataTable);
            catalogMetadataTable.Columns.Add("SchemaVersion", schemaVersionColumn);
            schemaVersionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(schemaVersionColumn);
            var seedVersionColumn = new Column("SeedVersion", "TEXT", catalogMetadataTable);
            catalogMetadataTable.Columns.Add("SeedVersion", seedVersionColumn);
            seedVersionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(seedVersionColumn);
            relationalModel.Tables.Add(("CatalogMetadata", null), catalogMetadataTable);
            var catalogMetadataTableMapping = new TableMapping(materialCatalogMetadataEntity, catalogMetadataTable, null);
            catalogMetadataTable.AddTypeMapping(catalogMetadataTableMapping, false);
            tableMappings.Add(catalogMetadataTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, materialCatalogMetadataEntity.FindProperty("Id")!, catalogMetadataTableMapping);
            RelationalModel.CreateColumnMapping(catalogIdColumn, materialCatalogMetadataEntity.FindProperty("CatalogId")!, catalogMetadataTableMapping);
            RelationalModel.CreateColumnMapping(schemaVersionColumn, materialCatalogMetadataEntity.FindProperty("SchemaVersion")!, catalogMetadataTableMapping);
            RelationalModel.CreateColumnMapping(seedVersionColumn, materialCatalogMetadataEntity.FindProperty("SeedVersion")!, catalogMetadataTableMapping);
            var pK_CatalogMetadata = new UniqueConstraint("PK_CatalogMetadata", catalogMetadataTable, new[] { idColumn });
            catalogMetadataTable.PrimaryKey = pK_CatalogMetadata;
            pK_CatalogMetadata.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_CatalogMetadata));
            var pK_CatalogMetadataKey = RelationalModel.GetKey(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity",
                new[] { "Id" });
            pK_CatalogMetadata.MappedKeys.Add(pK_CatalogMetadataKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_CatalogMetadataKey).Add(pK_CatalogMetadata);
            catalogMetadataTable.UniqueConstraints.Add("PK_CatalogMetadata", pK_CatalogMetadata);
            var iX_CatalogMetadata_CatalogId = new TableIndex(
            "IX_CatalogMetadata_CatalogId", catalogMetadataTable, new[] { catalogIdColumn }, true);
            iX_CatalogMetadata_CatalogId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_CatalogMetadata_CatalogId));
            var iX_CatalogMetadata_CatalogIdIx = RelationalModel.GetIndex(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity",
                new[] { "CatalogId" });
            iX_CatalogMetadata_CatalogId.MappedIndexes.Add(iX_CatalogMetadata_CatalogIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_CatalogMetadata_CatalogIdIx).Add(iX_CatalogMetadata_CatalogId);
            catalogMetadataTable.Indexes.Add("IX_CatalogMetadata_CatalogId", iX_CatalogMetadata_CatalogId);

            var materialEntity = FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            materialEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase = new TableBase("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity", null, relationalModel);
            var catalogIdColumnBase0 = new ColumnBase<ColumnMappingBase>("CatalogId", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("CatalogId", catalogIdColumnBase0);
            var constitutiveClassColumnBase = new ColumnBase<ColumnMappingBase>("ConstitutiveClass", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("ConstitutiveClass", constitutiveClassColumnBase);
            var designationColumnBase = new ColumnBase<ColumnMappingBase>("Designation", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Designation", designationColumnBase);
            var displayNameColumnBase = new ColumnBase<ColumnMappingBase>("DisplayName", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("DisplayName", displayNameColumnBase);
            var familyColumnBase = new ColumnBase<ColumnMappingBase>("Family", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Family", familyColumnBase);
            var firmamentPathColumnBase = new ColumnBase<ColumnMappingBase>("FirmamentPath", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("FirmamentPath", firmamentPathColumnBase);
            var gradeColumnBase = new ColumnBase<ColumnMappingBase>("Grade", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase)
            {
                IsNullable = true
            };
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Grade", gradeColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Id", idColumnBase0);
            var referenceConditionColumnBase = new ColumnBase<ColumnMappingBase>("ReferenceCondition", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("ReferenceCondition", referenceConditionColumnBase);
            var stableIdColumnBase = new ColumnBase<ColumnMappingBase>("StableId", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("StableId", stableIdColumnBase);
            var standardColumnBase = new ColumnBase<ColumnMappingBase>("Standard", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase)
            {
                IsNullable = true
            };
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Standard", standardColumnBase);
            var temperColumnBase = new ColumnBase<ColumnMappingBase>("Temper", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase)
            {
                IsNullable = true
            };
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.Columns.Add("Temper", temperColumnBase);
            relationalModel.DefaultTables.Add("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity", aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase = new TableMappingBase<ColumnMappingBase>(materialEntity, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase, null);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityTableBase.AddTypeMapping(aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase, false);
            defaultTableMappings0.Add(aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, materialEntity.FindProperty("Id")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)catalogIdColumnBase0, materialEntity.FindProperty("CatalogId")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)constitutiveClassColumnBase, materialEntity.FindProperty("ConstitutiveClass")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)designationColumnBase, materialEntity.FindProperty("Designation")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)displayNameColumnBase, materialEntity.FindProperty("DisplayName")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)familyColumnBase, materialEntity.FindProperty("Family")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)firmamentPathColumnBase, materialEntity.FindProperty("FirmamentPath")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)gradeColumnBase, materialEntity.FindProperty("Grade")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)referenceConditionColumnBase, materialEntity.FindProperty("ReferenceCondition")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)stableIdColumnBase, materialEntity.FindProperty("StableId")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)standardColumnBase, materialEntity.FindProperty("Standard")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)temperColumnBase, materialEntity.FindProperty("Temper")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialEntityMappingBase);

            var tableMappings0 = new List<TableMapping>();
            materialEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var materialsTable = new Table("Materials", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", materialsTable);
            materialsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            var catalogIdColumn0 = new Column("CatalogId", "TEXT", materialsTable);
            materialsTable.Columns.Add("CatalogId", catalogIdColumn0);
            catalogIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(catalogIdColumn0);
            var constitutiveClassColumn = new Column("ConstitutiveClass", "TEXT", materialsTable);
            materialsTable.Columns.Add("ConstitutiveClass", constitutiveClassColumn);
            constitutiveClassColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(constitutiveClassColumn);
            var designationColumn = new Column("Designation", "TEXT", materialsTable);
            materialsTable.Columns.Add("Designation", designationColumn);
            designationColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(designationColumn);
            var displayNameColumn = new Column("DisplayName", "TEXT", materialsTable);
            materialsTable.Columns.Add("DisplayName", displayNameColumn);
            displayNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(displayNameColumn);
            var familyColumn = new Column("Family", "TEXT", materialsTable);
            materialsTable.Columns.Add("Family", familyColumn);
            familyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(familyColumn);
            var firmamentPathColumn = new Column("FirmamentPath", "TEXT", materialsTable);
            materialsTable.Columns.Add("FirmamentPath", firmamentPathColumn);
            firmamentPathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(firmamentPathColumn);
            var gradeColumn = new Column("Grade", "TEXT", materialsTable)
            {
                IsNullable = true
            };
            materialsTable.Columns.Add("Grade", gradeColumn);
            gradeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(gradeColumn);
            var referenceConditionColumn = new Column("ReferenceCondition", "TEXT", materialsTable);
            materialsTable.Columns.Add("ReferenceCondition", referenceConditionColumn);
            referenceConditionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(referenceConditionColumn);
            var stableIdColumn = new Column("StableId", "TEXT", materialsTable);
            materialsTable.Columns.Add("StableId", stableIdColumn);
            stableIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(stableIdColumn);
            var standardColumn = new Column("Standard", "TEXT", materialsTable)
            {
                IsNullable = true
            };
            materialsTable.Columns.Add("Standard", standardColumn);
            standardColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(standardColumn);
            var temperColumn = new Column("Temper", "TEXT", materialsTable)
            {
                IsNullable = true
            };
            materialsTable.Columns.Add("Temper", temperColumn);
            temperColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(temperColumn);
            relationalModel.Tables.Add(("Materials", null), materialsTable);
            var materialsTableMapping = new TableMapping(materialEntity, materialsTable, null);
            materialsTable.AddTypeMapping(materialsTableMapping, false);
            tableMappings0.Add(materialsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, materialEntity.FindProperty("Id")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(catalogIdColumn0, materialEntity.FindProperty("CatalogId")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(constitutiveClassColumn, materialEntity.FindProperty("ConstitutiveClass")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(designationColumn, materialEntity.FindProperty("Designation")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(displayNameColumn, materialEntity.FindProperty("DisplayName")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(familyColumn, materialEntity.FindProperty("Family")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(firmamentPathColumn, materialEntity.FindProperty("FirmamentPath")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(gradeColumn, materialEntity.FindProperty("Grade")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(referenceConditionColumn, materialEntity.FindProperty("ReferenceCondition")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(stableIdColumn, materialEntity.FindProperty("StableId")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(standardColumn, materialEntity.FindProperty("Standard")!, materialsTableMapping);
            RelationalModel.CreateColumnMapping(temperColumn, materialEntity.FindProperty("Temper")!, materialsTableMapping);
            var pK_Materials = new UniqueConstraint("PK_Materials", materialsTable, new[] { idColumn0 });
            materialsTable.PrimaryKey = pK_Materials;
            pK_Materials.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Materials));
            var pK_MaterialsKey = RelationalModel.GetKey(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity",
                new[] { "Id" });
            pK_Materials.MappedKeys.Add(pK_MaterialsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MaterialsKey).Add(pK_Materials);
            materialsTable.UniqueConstraints.Add("PK_Materials", pK_Materials);
            var iX_Materials_CatalogId_StableId = new TableIndex(
            "IX_Materials_CatalogId_StableId", materialsTable, new[] { catalogIdColumn0, stableIdColumn }, true);
            iX_Materials_CatalogId_StableId.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_Materials_CatalogId_StableId));
            var iX_Materials_CatalogId_StableIdIx = RelationalModel.GetIndex(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity",
                new[] { "CatalogId", "StableId" });
            iX_Materials_CatalogId_StableId.MappedIndexes.Add(iX_Materials_CatalogId_StableIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Materials_CatalogId_StableIdIx).Add(iX_Materials_CatalogId_StableId);
            materialsTable.Indexes.Add("IX_Materials_CatalogId_StableId", iX_Materials_CatalogId_StableId);
            var iX_Materials_FirmamentPath = new TableIndex(
            "IX_Materials_FirmamentPath", materialsTable, new[] { firmamentPathColumn }, true);
            iX_Materials_FirmamentPath.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Materials_FirmamentPath));
            var iX_Materials_FirmamentPathIx = RelationalModel.GetIndex(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity",
                new[] { "FirmamentPath" });
            iX_Materials_FirmamentPath.MappedIndexes.Add(iX_Materials_FirmamentPathIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Materials_FirmamentPathIx).Add(iX_Materials_FirmamentPath);
            materialsTable.Indexes.Add("IX_Materials_FirmamentPath", iX_Materials_FirmamentPath);

            var materialPropertyEntity = FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            materialPropertyEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase = new TableBase("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity", null, relationalModel);
            var authorityColumnBase = new ColumnBase<ColumnMappingBase>("Authority", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("Authority", authorityColumnBase);
            var conditionColumnBase = new ColumnBase<ColumnMappingBase>("Condition", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("Condition", conditionColumnBase);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("Id", idColumnBase1);
            var kindColumnBase = new ColumnBase<ColumnMappingBase>("Kind", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("Kind", kindColumnBase);
            var materialIdColumnBase = new ColumnBase<ColumnMappingBase>("MaterialId", "INTEGER", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("MaterialId", materialIdColumnBase);
            var notesColumnBase = new ColumnBase<ColumnMappingBase>("Notes", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase)
            {
                IsNullable = true
            };
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("Notes", notesColumnBase);
            var referenceTemperatureKelvinColumnBase = new ColumnBase<ColumnMappingBase>("ReferenceTemperatureKelvin", "REAL", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase)
            {
                IsNullable = true
            };
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("ReferenceTemperatureKelvin", referenceTemperatureKelvinColumnBase);
            var sourceIdColumnBase = new ColumnBase<ColumnMappingBase>("SourceId", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("SourceId", sourceIdColumnBase);
            var sourceUriColumnBase = new ColumnBase<ColumnMappingBase>("SourceUri", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("SourceUri", sourceUriColumnBase);
            var unitSymbolColumnBase = new ColumnBase<ColumnMappingBase>("UnitSymbol", "TEXT", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("UnitSymbol", unitSymbolColumnBase);
            var valueSiColumnBase = new ColumnBase<ColumnMappingBase>("ValueSi", "REAL", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.Columns.Add("ValueSi", valueSiColumnBase);
            relationalModel.DefaultTables.Add("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity", aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase);
            var aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase = new TableMappingBase<ColumnMappingBase>(materialPropertyEntity, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase, null);
            aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityTableBase.AddTypeMapping(aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase, false);
            defaultTableMappings1.Add(aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, materialPropertyEntity.FindProperty("Id")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorityColumnBase, materialPropertyEntity.FindProperty("Authority")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)conditionColumnBase, materialPropertyEntity.FindProperty("Condition")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)kindColumnBase, materialPropertyEntity.FindProperty("Kind")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)materialIdColumnBase, materialPropertyEntity.FindProperty("MaterialId")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)notesColumnBase, materialPropertyEntity.FindProperty("Notes")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)referenceTemperatureKelvinColumnBase, materialPropertyEntity.FindProperty("ReferenceTemperatureKelvin")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sourceIdColumnBase, materialPropertyEntity.FindProperty("SourceId")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sourceUriColumnBase, materialPropertyEntity.FindProperty("SourceUri")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)unitSymbolColumnBase, materialPropertyEntity.FindProperty("UnitSymbol")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueSiColumnBase, materialPropertyEntity.FindProperty("ValueSi")!, aetherisKernelStandardLibraryMaterialsDatabaseMaterialPropertyEntityMappingBase);

            var tableMappings1 = new List<TableMapping>();
            materialPropertyEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var materialPropertiesTable = new Table("MaterialProperties", null, relationalModel);
            var idColumn1 = new Column("Id", "INTEGER", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn1);
            var authorityColumn = new Column("Authority", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("Authority", authorityColumn);
            authorityColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorityColumn);
            var conditionColumn = new Column("Condition", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("Condition", conditionColumn);
            conditionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(conditionColumn);
            var kindColumn = new Column("Kind", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("Kind", kindColumn);
            kindColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(kindColumn);
            var materialIdColumn = new Column("MaterialId", "INTEGER", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("MaterialId", materialIdColumn);
            materialIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(materialIdColumn);
            var notesColumn = new Column("Notes", "TEXT", materialPropertiesTable)
            {
                IsNullable = true
            };
            materialPropertiesTable.Columns.Add("Notes", notesColumn);
            notesColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(notesColumn);
            var referenceTemperatureKelvinColumn = new Column("ReferenceTemperatureKelvin", "REAL", materialPropertiesTable)
            {
                IsNullable = true
            };
            materialPropertiesTable.Columns.Add("ReferenceTemperatureKelvin", referenceTemperatureKelvinColumn);
            referenceTemperatureKelvinColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<double>(referenceTemperatureKelvinColumn);
            var sourceIdColumn = new Column("SourceId", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("SourceId", sourceIdColumn);
            sourceIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(sourceIdColumn);
            var sourceUriColumn = new Column("SourceUri", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("SourceUri", sourceUriColumn);
            sourceUriColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(sourceUriColumn);
            var unitSymbolColumn = new Column("UnitSymbol", "TEXT", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("UnitSymbol", unitSymbolColumn);
            unitSymbolColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(unitSymbolColumn);
            var valueSiColumn = new Column("ValueSi", "REAL", materialPropertiesTable);
            materialPropertiesTable.Columns.Add("ValueSi", valueSiColumn);
            valueSiColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<double>(valueSiColumn);
            relationalModel.Tables.Add(("MaterialProperties", null), materialPropertiesTable);
            var materialPropertiesTableMapping = new TableMapping(materialPropertyEntity, materialPropertiesTable, null);
            materialPropertiesTable.AddTypeMapping(materialPropertiesTableMapping, false);
            tableMappings1.Add(materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, materialPropertyEntity.FindProperty("Id")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(authorityColumn, materialPropertyEntity.FindProperty("Authority")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(conditionColumn, materialPropertyEntity.FindProperty("Condition")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(kindColumn, materialPropertyEntity.FindProperty("Kind")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(materialIdColumn, materialPropertyEntity.FindProperty("MaterialId")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(notesColumn, materialPropertyEntity.FindProperty("Notes")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(referenceTemperatureKelvinColumn, materialPropertyEntity.FindProperty("ReferenceTemperatureKelvin")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(sourceIdColumn, materialPropertyEntity.FindProperty("SourceId")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(sourceUriColumn, materialPropertyEntity.FindProperty("SourceUri")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(unitSymbolColumn, materialPropertyEntity.FindProperty("UnitSymbol")!, materialPropertiesTableMapping);
            RelationalModel.CreateColumnMapping(valueSiColumn, materialPropertyEntity.FindProperty("ValueSi")!, materialPropertiesTableMapping);
            var pK_MaterialProperties = new UniqueConstraint("PK_MaterialProperties", materialPropertiesTable, new[] { idColumn1 });
            materialPropertiesTable.PrimaryKey = pK_MaterialProperties;
            pK_MaterialProperties.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_MaterialProperties));
            var pK_MaterialPropertiesKey = RelationalModel.GetKey(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity",
                new[] { "Id" });
            pK_MaterialProperties.MappedKeys.Add(pK_MaterialPropertiesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MaterialPropertiesKey).Add(pK_MaterialProperties);
            materialPropertiesTable.UniqueConstraints.Add("PK_MaterialProperties", pK_MaterialProperties);
            var iX_MaterialProperties_MaterialId_Kind = new TableIndex(
            "IX_MaterialProperties_MaterialId_Kind", materialPropertiesTable, new[] { materialIdColumn, kindColumn }, true);
            iX_MaterialProperties_MaterialId_Kind.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_MaterialProperties_MaterialId_Kind));
            var iX_MaterialProperties_MaterialId_KindIx = RelationalModel.GetIndex(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity",
                new[] { "MaterialId", "Kind" });
            iX_MaterialProperties_MaterialId_Kind.MappedIndexes.Add(iX_MaterialProperties_MaterialId_KindIx);
            RelationalModel.GetOrCreateTableIndexes(iX_MaterialProperties_MaterialId_KindIx).Add(iX_MaterialProperties_MaterialId_Kind);
            materialPropertiesTable.Indexes.Add("IX_MaterialProperties_MaterialId_Kind", iX_MaterialProperties_MaterialId_Kind);
            var fK_MaterialProperties_Materials_MaterialId = new ForeignKeyConstraint(
                "FK_MaterialProperties_Materials_MaterialId", materialPropertiesTable, materialsTable,
                new[] { materialIdColumn },
                materialsTable.FindUniqueConstraint("PK_Materials")!, ReferentialAction.Cascade);
            fK_MaterialProperties_Materials_MaterialId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<int, int>(fK_MaterialProperties_Materials_MaterialId));
            var fK_MaterialProperties_Materials_MaterialIdFk = RelationalModel.GetForeignKey(this,
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity",
                new[] { "MaterialId" },
                "Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity",
                new[] { "Id" });
            fK_MaterialProperties_Materials_MaterialId.MappedForeignKeys.Add(fK_MaterialProperties_Materials_MaterialIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_MaterialProperties_Materials_MaterialIdFk).Add(fK_MaterialProperties_Materials_MaterialId);
            materialPropertiesTable.ForeignKeyConstraints.Add(fK_MaterialProperties_Materials_MaterialId);
            materialsTable.ReferencingForeignKeyConstraints.Add(fK_MaterialProperties_Materials_MaterialId);
            return relationalModel.MakeReadOnly();
        }
    }
}
