// <auto-generated />

using Aetheris.Kernel.StandardLibrary.Materials;
using Aetheris.Kernel.StandardLibrary.Materials.Database;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

#pragma warning disable EF9100 // Precompiled query is experimental
#pragma warning disable CS9270 // EF 10 tooling emits the supported legacy location form.

namespace Microsoft.EntityFrameworkCore.GeneratedInterceptors
{
    file static class EntityFrameworkCoreInterceptors
    {
        #region Query1

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 41, 58)]
        public static global::System.Linq.IQueryable<TEntity> Query1_AsNoTracking1<TEntity>(this global::System.Linq.IQueryable<TEntity> source)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext;
        }

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 41, 73)]
        public static TSource Query1_Single2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            Query1_Executor ??= Query1_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, TSource>)(Query1_Executor))(queryContext);
        }

        private static object Query1_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"c\".\"Id\", \"c\".\"CatalogId\", \"c\".\"SchemaVersion\", \"c\".\"SeedVersion\"\r\nFROM \"CatalogMetadata\" AS \"c\"\r\nWHERE \"c\".\"CatalogId\" = 'standard'\r\nLIMIT 2", "SELECT \"c\".\"Id\", \"c\".\"CatalogId\", \"c\".\"SchemaVersion\", \"c\".\"SeedVersion\"\r\nFROM \"CatalogMetadata\" AS \"c\"\r\nWHERE \"c\".\"CatalogId\" = 'standard'\r\nLIMIT 2", new IRelationalParameter[] { })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var emptySnapshot = Snapshot.Empty;
            var materialCatalogMetadataEntityEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialCatalogMetadataEntity");
            var materialCatalogMetadataEntityEntityType0 = ((RuntimeEntityType)(materialCatalogMetadataEntityEntityType));
            var materialCatalogMetadataEntityPrimaryKeyProperties = materialCatalogMetadataEntityEntityType.FindPrimaryKey().Properties;
            return MaterialCatalogMetadataEntity (QueryContext queryContext) => SingleQueryingEnumerable.Create(((RelationalQueryContext)(queryContext)), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), MaterialCatalogMetadataEntity (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(MaterialCatalogMetadataEntity);
    if (((object)(dataReader.GetInt32(0))) != null)
    {
        var shadowSnapshot1 = emptySnapshot;
        entityType1 = materialCatalogMetadataEntityEntityType;
        if (entityType1 == materialCatalogMetadataEntityEntityType)
        {
            var instance = UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_Ctor();
            UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_Id_Set(instance) = dataReader.GetInt32(0);
            UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_CatalogId_Set(instance) = dataReader.GetString(1);
            UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_SchemaVersion_Set(instance) = dataReader.GetInt32(2);
            UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_SeedVersion_Set(instance) = dataReader.GetString(3);
            if (instance is IInjectableService)
            {
                ((IInjectableService)(instance)).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.NoTracking, materialCatalogMetadataEntityEntityType0);
            }

            instance1 = instance;
        }
        else
        {
            instance1 = default(MaterialCatalogMetadataEntity);
        }
    }
    else
    {
        var keyValues1 = new object[]
        {
            ((object)(dataReader.GetInt32(0)))
        };
        ShapedQueryCompilingExpressionVisitor.CreateNullKeyValueInNoTrackingQuery(materialCatalogMetadataEntityEntityType, materialCatalogMetadataEntityPrimaryKeyProperties, keyValues1);
    }

    var entity = instance1;
    return entity;
}, typeof(MaterialCatalogDbContext), false, false, true).Single();
        }

        private static object Query1_Executor;

        #endregion Query1
        #region Query2

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 65, 62)]
        public static global::System.Linq.IQueryable<TEntity> Query2_AsNoTracking1<TEntity>(this global::System.Linq.IQueryable<TEntity> source)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext;
        }

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 66, 10)]
        public static global::Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<TEntity,TProperty> Query2_Include2<TEntity, TProperty>(this global::System.Linq.IQueryable<TEntity> source, global::System.Linq.Expressions.Expression<global::System.Func<TEntity,TProperty>> navigationPropertyPath)
        where TEntity : class
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TEntity>)source;
            return precompiledQueryContext.ToIncludable<TProperty>();
        }

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 67, 10)]
        public static global::System.Linq.IOrderedQueryable<TSource> Query2_OrderBy3<TSource, TKey>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,TKey>> keySelector)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            return precompiledQueryContext;
        }

        [InterceptsLocation(@"/_/Aetheris/Aetheris.Kernel.StandardLibrary/Materials/MaterialCatalog.cs", 68, 10)]
        public static TSource[] Query2_ToArray4<TSource>(this global::System.Collections.Generic.IEnumerable<TSource> source)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            Query2_Executor ??= Query2_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            var queryingEnumerable = ((Func<QueryContext, IEnumerable<TSource>>)(Query2_Executor))(queryContext);
            return queryingEnumerable.ToArray();
        }

        private static object Query2_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"m\".\"Id\", \"m\".\"CatalogId\", \"m\".\"ConstitutiveClass\", \"m\".\"Designation\", \"m\".\"DisplayName\", \"m\".\"Family\", \"m\".\"FirmamentPath\", \"m\".\"Grade\", \"m\".\"ReferenceCondition\", \"m\".\"StableId\", \"m\".\"Standard\", \"m\".\"Temper\", \"m0\".\"Id\", \"m0\".\"Authority\", \"m0\".\"Condition\", \"m0\".\"Kind\", \"m0\".\"MaterialId\", \"m0\".\"Notes\", \"m0\".\"ReferenceTemperatureKelvin\", \"m0\".\"SourceId\", \"m0\".\"SourceUri\", \"m0\".\"UnitSymbol\", \"m0\".\"ValueSi\"\r\nFROM \"Materials\" AS \"m\"\r\nLEFT JOIN \"MaterialProperties\" AS \"m0\" ON \"m\".\"Id\" = \"m0\".\"MaterialId\"\r\nORDER BY \"m\".\"StableId\", \"m\".\"Id\"", "SELECT \"m\".\"Id\", \"m\".\"CatalogId\", \"m\".\"ConstitutiveClass\", \"m\".\"Designation\", \"m\".\"DisplayName\", \"m\".\"Family\", \"m\".\"FirmamentPath\", \"m\".\"Grade\", \"m\".\"ReferenceCondition\", \"m\".\"StableId\", \"m\".\"Standard\", \"m\".\"Temper\", \"m0\".\"Id\", \"m0\".\"Authority\", \"m0\".\"Condition\", \"m0\".\"Kind\", \"m0\".\"MaterialId\", \"m0\".\"Notes\", \"m0\".\"ReferenceTemperatureKelvin\", \"m0\".\"SourceId\", \"m0\".\"SourceUri\", \"m0\".\"UnitSymbol\", \"m0\".\"ValueSi\"\r\nFROM \"Materials\" AS \"m\"\r\nLEFT JOIN \"MaterialProperties\" AS \"m0\" ON \"m\".\"Id\" = \"m0\".\"MaterialId\"\r\nORDER BY \"m\".\"StableId\", \"m\".\"Id\"", new IRelationalParameter[] { })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var emptySnapshot = Snapshot.Empty;
            var model = materializerLiftableConstantContext.Dependencies.Model;
            var materialEntityEntityType = model.FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialEntity");
            var constitutiveClassProperty = ((IPropertyBase)(((ITypeBase)materialEntityEntityType).FindProperty("ConstitutiveClass")));
            var materialEntityEntityType0 = ((RuntimeEntityType)(materialEntityEntityType));
            var materialEntityPrimaryKeyProperties = materialEntityEntityType.FindPrimaryKey().Properties;
            var parentIdentifierLambda = object[] (QueryContext queryContext, DbDataReader dataReader) => new object[]
{
    ((object)(((int? )(dataReader.GetInt32(0)))))
};
            var findNavigation = materialEntityEntityType.FindNavigation("Properties");
            var propertiesNavigation = ((INavigationBase)(findNavigation));
            var propertiesNavigationCollectionAccessor = ((IPropertyBase)findNavigation).GetCollectionAccessor();
            var selfIdentifierLambda = object[] (QueryContext queryContext, DbDataReader dataReader) => new object[]
{
    ((object)((dataReader.IsDBNull(12) ? default(int? ) : ((int? )(dataReader.GetInt32(12))))))
};
            var parentIdentifierValueComparers = new Func<object, object, bool>[]
{
    bool (object left, object right) => (left == null ? right == null : right != null && ((int)(left)) == ((int)(right)))
};
            var materialPropertyEntityEntityType = model.FindEntityType("Aetheris.Kernel.StandardLibrary.Materials.Database.MaterialPropertyEntity");
            var authorityProperty = ((IPropertyBase)(((ITypeBase)materialPropertyEntityEntityType).FindProperty("Authority")));
            var kindProperty = ((IPropertyBase)(((ITypeBase)materialPropertyEntityEntityType).FindProperty("Kind")));
            var materialPropertyEntityEntityType0 = ((RuntimeEntityType)(materialPropertyEntityEntityType));
            var materialInverseNavigation = ((INavigationBase)(materialPropertyEntityEntityType.FindNavigation("Material")));
            return IEnumerable<MaterialEntity> (QueryContext queryContext) => SingleQueryingEnumerable.Create(((RelationalQueryContext)(queryContext)), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), MaterialEntity (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    if (resultContext.Values == null)
    {
        IEntityType entityType1 = default(IEntityType);
        var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
        var instance1 = default(MaterialEntity);
        if (((object)(dataReader.GetInt32(0))) != null)
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = materialEntityEntityType;
            if (entityType1 == materialEntityEntityType)
            {
                var instance = UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Ctor();
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_CatalogId_Set(instance) = dataReader.GetString(1);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_ConstitutiveClass_Set(instance) = ((ValueConverter<MaterialConstitutiveClass, string>)(((IReadOnlyProperty)(constitutiveClassProperty)).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetString(2));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Designation_Set(instance) = dataReader.GetString(3);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_DisplayName_Set(instance) = dataReader.GetString(4);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Family_Set(instance) = dataReader.GetString(5);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_FirmamentPath_Set(instance) = dataReader.GetString(6);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Grade_Set(instance) = (dataReader.IsDBNull(7) ? default(string) : dataReader.GetString(7));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_ReferenceCondition_Set(instance) = dataReader.GetString(8);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_StableId_Set(instance) = dataReader.GetString(9);
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Standard_Set(instance) = (dataReader.IsDBNull(10) ? default(string) : dataReader.GetString(10));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Temper_Set(instance) = (dataReader.IsDBNull(11) ? default(string) : dataReader.GetString(11));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)(instance)).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.NoTracking, materialEntityEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(MaterialEntity);
            }
        }
        else
        {
            var keyValues1 = new object[]
            {
                ((object)(dataReader.GetInt32(0)))
            };
            ShapedQueryCompilingExpressionVisitor.CreateNullKeyValueInNoTrackingQuery(materialEntityEntityType, materialEntityPrimaryKeyProperties, keyValues1);
        }

        var entity = instance1;
        resultContext.Values = new object[]
        {
            entity
        };
        RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.InitializeIncludeCollection<MaterialEntity, MaterialEntity>(0, queryContext, dataReader, resultCoordinator, ((MaterialEntity)(resultContext.Values[0])), parentIdentifierLambda, parentIdentifierLambda, propertiesNavigation, propertiesNavigationCollectionAccessor, false, true);
    }

    RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection(0, queryContext, dataReader, resultCoordinator, parentIdentifierLambda, parentIdentifierLambda, selfIdentifierLambda, parentIdentifierValueComparers, parentIdentifierValueComparers, parentIdentifierValueComparers, MaterialPropertyEntity (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
    {
        IEntityType entityType2 = default(IEntityType);
        var materializationContext2 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
        var instance2 = default(MaterialPropertyEntity);
        if ((dataReader.IsDBNull(12) ? default(object) : ((object)(dataReader.GetInt32(12)))) != null)
        {
            var shadowSnapshot2 = emptySnapshot;
            entityType2 = materialPropertyEntityEntityType;
            if (entityType2 == materialPropertyEntityEntityType)
            {
                var instance = UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Ctor();
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Id_Set(instance) = (dataReader.IsDBNull(12) ? default(int) : dataReader.GetInt32(12));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Authority_Set(instance) = (dataReader.IsDBNull(13) ? default(MaterialPropertyAuthority) : ((ValueConverter<MaterialPropertyAuthority, string>)(((IReadOnlyProperty)(authorityProperty)).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetString(13)));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Condition_Set(instance) = (dataReader.IsDBNull(14) ? default(string) : dataReader.GetString(14));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Kind_Set(instance) = (dataReader.IsDBNull(15) ? default(MaterialPropertyKind) : ((ValueConverter<MaterialPropertyKind, string>)(((IReadOnlyProperty)(kindProperty)).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetString(15)));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_MaterialId_Set(instance) = (dataReader.IsDBNull(16) ? default(int) : dataReader.GetInt32(16));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Notes_Set(instance) = (dataReader.IsDBNull(17) ? default(string) : dataReader.GetString(17));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_ReferenceTemperatureKelvin_Set(instance) = (dataReader.IsDBNull(18) ? default(double? ) : ((double? )(dataReader.GetDouble(18))));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_SourceId_Set(instance) = (dataReader.IsDBNull(19) ? default(string) : dataReader.GetString(19));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_SourceUri_Set(instance) = (dataReader.IsDBNull(20) ? default(string) : dataReader.GetString(20));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_UnitSymbol_Set(instance) = (dataReader.IsDBNull(21) ? default(string) : dataReader.GetString(21));
                UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_ValueSi_Set(instance) = (dataReader.IsDBNull(22) ? default(double) : dataReader.GetDouble(22));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)(instance)).Injected(materializationContext2.Context, instance, QueryTrackingBehavior.NoTracking, materialPropertyEntityEntityType0);
                }

                instance2 = instance;
            }
            else
            {
                instance2 = default(MaterialPropertyEntity);
            }
        }

        var entity = instance2;
        return entity;
    }, materialInverseNavigation, (MaterialEntity unnamed1, MaterialPropertyEntity unnamed2) =>
    {
        propertiesNavigationCollectionAccessor.Add(unnamed1, unnamed2, true);
        UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Material_Set(unnamed2) = unnamed1;
    }, false);
    return (resultCoordinator.ResultReady ? ((MaterialEntity)(resultContext.Values[0])) : default(MaterialEntity));
}, typeof(MaterialCatalogDbContext), false, false, true);
        }

        private static object Query2_Executor;

        #endregion Query2
        #region Unsafe accessors
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_Id_Set(MaterialCatalogMetadataEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CatalogId>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_CatalogId_Set(MaterialCatalogMetadataEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SchemaVersion>k__BackingField")]
private static extern ref int UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_SchemaVersion_Set(MaterialCatalogMetadataEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SeedVersion>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_SeedVersion_Set(MaterialCatalogMetadataEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
private static extern MaterialCatalogMetadataEntity UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialCatalogMetadataEntity_Ctor();
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Id_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CatalogId>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_CatalogId_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConstitutiveClass>k__BackingField")]
private static extern ref MaterialConstitutiveClass UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_ConstitutiveClass_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Designation>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Designation_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DisplayName>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_DisplayName_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Family>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Family_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FirmamentPath>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_FirmamentPath_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Grade>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Grade_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReferenceCondition>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_ReferenceCondition_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StableId>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_StableId_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Standard>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Standard_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Temper>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Temper_Set(MaterialEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Id_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Authority>k__BackingField")]
private static extern ref MaterialPropertyAuthority UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Authority_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Condition>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Condition_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Kind>k__BackingField")]
private static extern ref MaterialPropertyKind UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Kind_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaterialId>k__BackingField")]
private static extern ref int UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_MaterialId_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Notes_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReferenceTemperatureKelvin>k__BackingField")]
private static extern ref double? UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_ReferenceTemperatureKelvin_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceId>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_SourceId_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceUri>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_SourceUri_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UnitSymbol>k__BackingField")]
private static extern ref string UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_UnitSymbol_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ValueSi>k__BackingField")]
private static extern ref double UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_ValueSi_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Material>k__BackingField")]
private static extern ref MaterialEntity UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Material_Set(MaterialPropertyEntity instance);
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
private static extern MaterialEntity UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialEntity_Ctor();
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
private static extern MaterialPropertyEntity UnsafeAccessor_Aetheris_Kernel_StandardLibrary_Materials_Database_MaterialPropertyEntity_Ctor();
        #endregion Unsafe accessors
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(string filePath, int line, int column) { }
    }
}
