// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aetheris.Kernel.StandardLibrary.Materials.Database.CompiledModel
{
    public static class MaterialPropertyEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Authority>k__BackingField")]
        public static extern ref MaterialPropertyAuthority Authority(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Condition>k__BackingField")]
        public static extern ref string Condition(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Kind>k__BackingField")]
        public static extern ref MaterialPropertyKind Kind(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaterialId>k__BackingField")]
        public static extern ref int MaterialId(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
        public static extern ref string Notes(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReferenceTemperatureKelvin>k__BackingField")]
        public static extern ref double? ReferenceTemperatureKelvin(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceId>k__BackingField")]
        public static extern ref string SourceId(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceUri>k__BackingField")]
        public static extern ref string SourceUri(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UnitSymbol>k__BackingField")]
        public static extern ref string UnitSymbol(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ValueSi>k__BackingField")]
        public static extern ref double ValueSi(MaterialPropertyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Material>k__BackingField")]
        public static extern ref MaterialEntity Material(MaterialPropertyEntity @this);
    }
}
