// Generated by vd-wgsl/1. Do not edit.
struct vd_s0 {
    m0: vec3<f32>,
}

struct vd_s1 {
    m0: vec4<f32>,
}

struct vd_s2 {
    m0: vec4<f32>,
    m1: vec4<f32>,
}

struct vd_io3 {
    @location(0) m0: vec3<f32>,
}

struct vd_io4 {
    @builtin(position) m0: vec4<f32>,
    @location(0) @interpolate(perspective) m1: vec4<f32>,
}

struct vd_io5 {
    @builtin(position) m0: vec4<f32>,
    @location(0) @interpolate(perspective) m1: vec4<f32>,
}

struct vd_io6 {
    @location(0) m0: vec4<f32>,
}


fn vd_f0(vd_l0: f32) -> vec3<f32> {
    return vec3<f32>(2f, 0.25f, vd_l0);
}

fn vd_f1(vd_l1: f32) -> vec3<f32> {
    return vec3<f32>(3f, 0.12f, vd_l1);
}

fn vd_f2(vd_l2: vd_s2) -> vd_s1 {
    return vd_s1(vec4<f32>(vd_f6(vd_l2.m1.x, vd_l2.m1.y, vd_l2.m1.z, vd_l2.m1.w), 1f));
}

fn vd_f3() -> vec3<f32> {
    return vec3<f32>(0f, 0f, 0f);
}

fn vd_f4(vd_l3: f32) -> u32 {
    if ((vd_l3 >= 0.9f)) {
        return 100u;
    }
    if ((vd_l3 >= 0.7f)) {
        return 80u;
    }
    if ((vd_l3 >= 0.5f)) {
        return 60u;
    }
    if ((vd_l3 >= 0.3f)) {
        return 40u;
    }
    if ((vd_l3 >= 0.1f)) {
        return 20u;
    }
    return 0u;
}

fn vd_f5(vd_l4: f32) -> vec3<f32> {
    return vec3<f32>(1f, 0.5f, vd_l4);
}

fn vd_f6(vd_l5: f32, vd_l6: f32, vd_l7: f32, vd_l8: f32) -> vec3<f32> {
    let vd_l9: f32 = (((vd_l5 * vd_l6) * vd_l7) * (1f - vd_l8));
    let vd_l10: f32 = (((vd_l5 * vd_l6) * (1f - vd_l7)) * (1f - vd_l8));
    let vd_l11: f32 = max((1f - vd_l5), max((1f - vd_l6), (vd_l8 * (1f - vd_l7))));
    return vd_f7(vd_l5, vd_l6, vd_l7, vd_l8, vd_l9, vd_l10, vd_l11);
}

fn vd_f7(vd_l12: f32, vd_l13: f32, vd_l14: f32, vd_l15: f32, vd_l16: f32, vd_l17: f32, vd_l18: f32) -> vec3<f32> {
    var vd_l19: u32 = 0u;
    var vd_l20: u32 = 0u;
    if (true) {
        let vd_l21: u32 = vd_f4(vd_l18);
        if (((vd_l19 == 0u) || (vd_l21 > vd_l20))) {
            vd_l20 = vd_l21;
            vd_l19 = 1u;
        }
    }
    if ((((vd_l12 > 0.8f) && (vd_l13 > 0.7f)) && (vd_l15 < 0.2f))) {
        let vd_l22: u32 = vd_f4(vd_l16);
        if (((vd_l19 == 0u) || (vd_l22 > vd_l20))) {
            vd_l20 = vd_l22;
            vd_l19 = 2u;
        }
    }
    if ((((vd_l12 > 0.8f) && (vd_l13 > 0.5f)) && (vd_l15 < 0.2f))) {
        let vd_l23: u32 = vd_f4(vd_l17);
        if (((vd_l19 == 0u) || (vd_l23 > vd_l20))) {
            vd_l20 = vd_l23;
            vd_l19 = 3u;
        }
    }
    if (((((vd_l12 > 0.8f) && (vd_l13 > 0.8f)) && (vd_l14 > 0.8f)) && (vd_l15 >= 0.2f))) {
        let vd_l24: u32 = vd_f4(((vd_l12 * vd_l13) * vd_l14));
        if (((vd_l19 == 0u) || (vd_l24 > vd_l20))) {
            vd_l20 = vd_l24;
            vd_l19 = 4u;
        }
    }
    if ((vd_l19 == 1u)) {
        return vd_f3();
    }
    if ((vd_l19 == 2u)) {
        return vd_f5(vd_l16);
    }
    if ((vd_l19 == 3u)) {
        return vd_f0(vd_l17);
    }
    if ((vd_l19 == 4u)) {
        return vd_f1(((vd_l12 * vd_l13) * vd_l14));
    }
    return vd_f3();
}

fn vd_f8(vd_l25: vd_s0) -> vd_s2 {
    return vd_s2(vec4<f32>(vd_l25.m0, 1f), vec4<f32>(1f, 1f, 1f, 0f));
}

@vertex
fn vd_vertex(vd_l26: vd_io3) -> vd_io4 {
    let vd_l27: vd_s2 = vd_f8(vd_s0(vd_l26.m0));
    return vd_io4(vd_l27.m0, vd_l27.m1);
}

@fragment
fn vd_fragment(vd_l28: vd_io5) -> vd_io6 {
    let vd_l29: vd_s1 = vd_f2(vd_s2(vd_l28.m0, vd_l28.m1));
    return vd_io6(vd_l29.m0);
}


// Source: fixtures/three-telos/temporal-policy.v.ts
// Semantic hash: 140e888b696dcf0d8ec8de3a53a74e265517c8b2ff6319596a3c05f3fba57984
// Static linkage from compiler-owned FunctionNames.
fn telosPolicy(depth: f32, motion: f32, color: f32, edge: f32) -> vec3<f32> {
    return vd_f6(depth, motion, color, edge);
}
