using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Aetheris.Continuum.Experiments.Attention;

var repository=FindRoot(AppContext.BaseDirectory);var output=Path.Combine(repository,"docs","continuum","artifacts","attention-e1");Directory.CreateDirectory(output);
var options=new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase};var compact=new JsonSerializerOptions(options){WriteIndented=false};
var benchmark=AttentionE1Experiments.Run();
WriteJson("benchmark-matrix.json",benchmark.Methods.Where(x=>x.Matrix=="benchmark").Select(Trim));
foreach(var matrix in new[]{"ablation","contrast","anisotropy","orientation","authority","scaling","weight-ablation"})WriteJson($"{matrix}-matrix.json",benchmark.Methods.Where(x=>x.Matrix==matrix).Select(Trim));
WriteJson("residual-histories.json",benchmark.Methods.Select(x=>new{x.Matrix,x.Scenario,x.Method,x.PointsPerAxis,x.ResidualHistory}));
WriteJson("mathematical-contracts.json",benchmark.Contracts);WriteJson("mode-analysis.json",benchmark.ModeAnalysis);WriteJson("interaction-graphs.json",benchmark.InteractionSamples);WriteJson("information-advantage-audit.json",benchmark.InformationAudit);
WriteJson("setup-per-iteration-cost.json",new{setupEstimateNote="Graph setup estimates count numeric scoring FLOPs only; comparison-sort work is reported separately because comparisons are not FLOPs.",rows=benchmark.Methods.Select(x=>new{x.Matrix,x.Scenario,x.Method,x.PointsPerAxis,x.SetupMilliseconds,estimatedSetupScoringFlops=SetupFlops(x),estimatedSortComparisons=SortComparisons(x),x.PreconditionerFlops,x.PreconditionerMilliseconds,x.Iterations,perApplicationMilliseconds=x.Iterations==0?0:x.PreconditionerMilliseconds/x.Iterations,x.MemoryBytes,x.InteractionsPerUnknown})});
WriteJson("oct-three-field-review.json",new{
 schema="aetheris-continuum-attention-e1-oct-source-review-v1",repository="oct/Experiments/ContinuumComputabilityBoundary",sourcePaths=new[]{"REPORT.md (M14-M20)","M14/continuum_computability_boundary_m14_probe.oct","M15/continuum_computability_boundary_m15_probe.oct","M16/continuum_computability_boundary_m16_probe.oct","M17/REPORT.md and continuum_computability_boundary_m17_probe.oct","M18/REPORT.md and probe","M19/REPORT.md and continuum_computability_boundary_m19_probe.oct","M20/REPORT.md and continuum_computability_boundary_m20_probe.oct","M27/MechanicsContinuumM27Report.md","M28/MechanicsContinuumM28Report.md","M31/MechanicsContinuumM31Report.md","M34/MechanicsContinuumM34Report.md"},
 geometry=new{fact="Occupancy/coverage first, then cell-centred signed distance to a circle (negative inside), abs(SDF)<=dx narrow-band proximity, and local SDF-gradient normals with perpendicular tangents. It was a fixed 6x6 Cartesian carrier, not CAD topology.",storage="Float arrays for coverage/SDF and orientation components/strength on every lattice cell; edge fields were derived on implicit four-neighbor adjacency.",downstream="Orientation-weighted one-step diffusion-like transfer and later local constitutive frames."},
 material=new{fact="A separate interior orientation/direction carrier, initially constant, then region-tagged, then two seeded directions propagated by deterministic four-neighbor averaging for eight fixed sweeps.",storage="Ox, Oy, Strength arrays plus a descriptive rule.",downstream="Geometry/material orientation composition, anisotropic edge weights, and tangent/normal constitutive response."},
 authority=new{fact="Local confidence/ownership for composing geometry-derived and material-derived carriers: geometry confidence came from SDF proximity (with a floor), material confidence from explicit strength or a heterogeneous left-high/right-low map. It was not load direction, source ownership, or a PDE boundary-condition field.",storage="GeometryConfidence and MaterialConfidence scalar arrays, independently built in M20.",downstream="Hard winner/tie blending, material usage scaling, optional transport feedback; later evidence supported narrow coupling-specific constitutive modulation, not whole-response scaling or iteration policy."},
 supported=new[]{"SDF supplied proximity and deterministic orientation not identical to occupancy.","Explicit geometry orientation changed the same local downstream operator and improved circle-boundary tangential fidelity in that fixture.","Separate geometry and material carriers were computationally distinguishable; seeded fixed-pass material transport reduced a hand-created region seam.","Explicit heterogeneous confidence changed carrier coupling; coupling-specific authority perturbations preserved local constitutive semantics better than scalar whole-response attenuation.","Tiny fixed correction loops reduced the experiment's mismatch metric with diminishing returns."},
 speculative=new[]{"The 6x6 circle one-step metrics did not demonstrate a PDE solver or preconditioner advantage.","Seed transport was a hand-designed fixed-sweep organizer, not a physical material law.","Confidence maps were synthetic policies, not inferred or validated boundary-condition authority.","Later global-consistency loops explicitly avoided matrix assembly and generic convergence, so they do not establish scalable continuum solve behavior."},
 obsolete=new[]{"Coverage/SDF as the primary representation of exact boundary identity and normals is obsolete where Aetheris exact BRep+CIR supplies analytic topology/geometry.","Inferring cut occupancy or interface orientation by sampling is obsolete for cut cells where exact cut metadata exists.","Fixed 6x6 implicit topology and circle-specific tangent construction are fixture assumptions, not production Continuum requirements.","What remains useful is the separation of geometry, material, and confidence/policy carriers and the demand that coupling stay explicit."}
});
WriteCsv("matched-budget-table.csv",benchmark.Methods,"matrix,scenario,method,n,unknowns,operator_nonzeros,undirected_edges,interactions_per_unknown,preconditioner_flops,memory_bytes,setup_ms,runtime_ms,preconditioner_ms,iterations,relative_residual,relative_solution_error");
var deterministic=new{benchmark.Schema,benchmark.Hypothesis,benchmark.Pde,benchmark.Discretization,benchmark.BudgetRule,benchmark.ResultClassification,methods=benchmark.Methods.Select(x=>new{x.Matrix,x.Scenario,x.Method,x.PointsPerAxis,x.Unknowns,x.OperatorNonzeros,x.UndirectedInteractions,x.InteractionsPerUnknown,x.PreconditionerFlops,x.MemoryBytes,x.Iterations,x.RelativeResidual,x.RelativeSolutionError,x.ResidualHistory}),benchmark.Contracts,benchmark.ModeAnalysis,benchmark.InteractionSamples,benchmark.InformationAudit};
var json=JsonSerializer.Serialize(deterministic,compact)+Environment.NewLine;File.WriteAllText(Path.Combine(output,"deterministic-results.json"),json,new UTF8Encoding(false));WriteJson("deterministic-hash.json",new{algorithm="SHA-256",excludes=new[]{"runtime and setup timing"},sha256=Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(json)))});
Console.WriteLine(JsonSerializer.Serialize(new{output,benchmark.ResultClassification,primary=benchmark.Methods.Where(x=>x.Scenario=="primary").Select(x=>new{x.Matrix,x.Method,x.Iterations,x.RuntimeMilliseconds,x.RelativeResidual})},options));

object Trim(AttentionE1MethodResult x)=>x with{ResidualHistory=[]};
void WriteJson(string name,object value)=>File.WriteAllText(Path.Combine(output,name),JsonSerializer.Serialize(value,options)+Environment.NewLine,new UTF8Encoding(false));
void WriteCsv(string name,IEnumerable<AttentionE1MethodResult> rows,string header)=>File.WriteAllLines(Path.Combine(output,name),new[]{header}.Concat(rows.Select(x=>string.Join(',',Csv(x.Matrix),Csv(x.Scenario),Csv(x.Method),x.PointsPerAxis,x.Unknowns,x.OperatorNonzeros,x.UndirectedInteractions,R(x.InteractionsPerUnknown),x.PreconditionerFlops,x.MemoryBytes,R(x.SetupMilliseconds),R(x.RuntimeMilliseconds),R(x.PreconditionerMilliseconds),x.Iterations,R(x.RelativeResidual),R(x.RelativeSolutionError)))),new UTF8Encoding(false));
static string R(double x)=>x.ToString("R",CultureInfo.InvariantCulture);static string Csv(string x)=>$"\"{x.Replace("\"","\"\"")}\"";
static long CandidateCount(int n)=>3L*(n-1)*n*n+6L*(n-1)*(n-1)*n+4L*(n-1)*(n-1)*(n-1)+3L*(n-2)*n*n+4L*(n-2)*(n-1)*n;
static long SetupFlops(AttentionE1MethodResult x)=>!x.Method.StartsWith("graph-")?0:CandidateCount(x.PointsPerAxis)*(x.Method.Contains("coefficient-only")?45L:80L);
static long SortComparisons(AttentionE1MethodResult x){var c=CandidateCount(x.PointsPerAxis);return !x.Method.StartsWith("graph-")?0:(long)Math.Ceiling(c*Math.Log2(c));}
static string FindRoot(string start){for(var d=new DirectoryInfo(start);d is not null;d=d.Parent)if(File.Exists(Path.Combine(d.FullName,"Aetheris.slnx")))return d.FullName;throw new DirectoryNotFoundException();}
